### ISSUE TITLE
cw (change-word) when editing HTML tags doesn't update the closing tag

### ISSUE THREAD

**Issue by SirCmpwn** [jaredpar/VsVim#1160]
When I use dwi to change a tag name in an HTML file, the closing tag updates automatically. When I use cw, it does not.

**Comment by ricksladkey** [comment]
At the head of VsVim master, with Visual Studio 2017, the renaming of the closing tag occurs automatically with either `cw` or `dwi` in a XAML file. This isn't a service provided by VsVim, and it in fact interferes with VsVim when you are rename the *closing* tag, which caused simultaneous edits to the opening tag, which confuses VsVim.

As a specific example, using the command `x` on the `T` in the closing tag of this text (where the vertical bar represents the caret):

```
<TextBlock></|TextBlock>
```

results in:

```
<extBlock></e|xtBlock>
```

instead of:

```
<extBlock></|extBlock>
```

and similarly using `cw` or `dw` on the closing tag results in:

```
<></>
```

with the caret being placed somewhere in the subsequent line.

**Comment by ricksladkey** [comment]
In general, any time we modify a text buffer (insert/delete/replace), we cannot assume a position number from before the modification is valid after the modification, because a language service may perform edits in response to our modification. In practice, this only matters if the edit occurs before the caret position because then it affects the position.
