### ISSUE TITLE
"dip" and "cip" do not work

### ISSUE THREAD

**Issue by opsound** [jaredpar/VsVim#1332]
"delete in paragraph" and "change in paragraph" do not work.

**Comment by Mharlin** [comment]
I could not find the implementation for the in paragraph motion, could you give me a hint on where to look? This feels like something I could handle

**Comment by Kantis** [comment]
From what I can tell the in paragraph motion isn't implemented at all, which is why nothing happens when trying to issue it. I might be wrong though :)

**Comment by jaredpar** [comment]
@Mharlin these are implemented in MotionUtil.fs.  This file holds the majority of motion implementations.

https://github.com/jaredpar/VsVim/blob/master/Src/VimCore/MotionUtil.fs#L2359

**Comment by aguevara** [comment]
I just started using VsVim in the past few weeks, love it @jaredpar, thanks so much!
I'm encountering similar problem, ip text object seems not implemented? (e.g. vip)
Has anyone had time to add that feature? Would be great to see it!

**Comment by jaredpar** [comment]
@aguevara text object motions are largely implemented.  They due have some issues due to the complexity of their implementation + relative lack of documentation.  I'm definitely interested in looking into issue you find in them though.

**Comment by aguevara** [comment]
Your comment from mar 2014 "the ip motion is implemented" made me wonder, because it's not working for me either like @opsound . vap works for me, just not vip. I realize the difference is small, but vip is actually more useful to me most of the time. vip doesn't include the whitespace boundary around the paragraph in the visual block as vap does. Incidentally, I also just compared vap in vsvim to vap in Vim, and noticed that vsvim selects the space before the paragraph when using vap, whereas Vim selects the whitespace after but not before. In VsVim I tried a few other i text objects and they didn't work, but a's did, so I started out assuming the i text objects just weren't implemented. (:h text-objects)

**Comment by Predelnik** [comment]
:+1: I also would like to see this fixed

**Comment by nandox** [comment]
Same problem with vip, not working and would like to use it.

**Comment by jhamm** [comment]
I have a PR that adds the inner paragraph motion.
