### ISSUE TITLE
Highlighting in Insert Mode goes to Visual Mode, but goes back to Command Mode

### ISSUE THREAD

**Issue by tjcertified** [jaredpar/VsVim#1373]
Steps to Reproduce:
1) Go to Insert Mode
2) Highlight text
3) See the cursor change to block
4) Hit 'Esc'
5) See mode is command mode

Performing same steps in Vim takes you back to Insert Mode. I am using VS 2012 with Resharper and Productivity Power Tools

**Comment by ricksladkey** [comment]
Is there anyone who has Resharper installed who could test whether this still occurs with the latest VsVim? Thanks!

**Comment by ricksladkey** [comment]
@dhmgit Yes, the only way to highlight text in insert mode with `:behave xterm` is to use the mouse. Ideally, all three should be tested:

- `:behave xterm` - double-click or drag with mouse from insert mode
- `:behave mswin` - double-click or drag with mouse from insert mode
- `:behave xterm` - shift or ctrl-shift plus arrows from insert mode

In each case, pressing `<Esc>` should return to insert mode.

**Comment by ricksladkey** [comment]
BTW, the default for vim and for VsVim for users without an rc file is `:behave mswin`. For the record, I also use `:behave mswin` because it integrates so well with Visual Studio.

**Comment by dhmgit** [comment]
Experimenting a bit with the above settings, I see that when gVim is set to selectmode="" and keymodel="startsel,stopsel", then selecting text with the keyboard in INSERT mode enters "(insert) VISUAL" mode.  Switching to selectmode="key" causes "(insert) SELECT" mode to be entered instead.  With the same settings in VsVim, it enters VISUAL and SELECT modes, respectively, instead of the hybrid modes.  

In gVim, when ESC is pressed in either of these hybrid modes, it naturally reverts to INSERT mode.  In VsVim, ESC is followed by a very brief switch to INSERT mode on its way back to NORMAL mode.  If you're not paying close attention, you wouldn't notice "-- INSERT --" flash up on the screen.

In VsVim, the same behavior is exhibited regardless of whether text is selected with the mouse or the keyboard.  For whatever reason I'm not able to select text with the mouse in gVim -- maybe because I run it in a console window and the console itself enters its own select mode.   I guess I never tried using the mouse in gVim before now.

Note that disabling ReSharper had no effect on any of the above described behaviors, so I doubt it is contributing to this issue.

Ultimately, I think this issue needs to stay open.  It looks like it is caused by VsVim not entering the hybrid "(insert) SELECT/VISUAL" mode from INSERT mode as expected, so it has no chance of reverting back to the proper mode after ESC is pressed.

**Comment by ricksladkey** [comment]
It is true that VsVim doesn't notate the visual or select mode as being initiated from insert mode, but otherwise, my installation without Resharper does *not* go to normal mode in any of the three use cases, but correctly goes back to insert mode. So our "no Resharper" results disagree.

**Comment by dhmgit** [comment]
That's very interesting.  Maybe disabling ReSharper isn't quite enough and it needs to be fully uninstalled to prevent interference.  In any case, I can confirm that the issue is still present!
