### ISSUE TITLE
Repeating ignores <BS>

### ISSUE THREAD

**Issue by MartinRykfors** [jaredpar/VsVim#1532]
Start with the following text with the cursor at the beginning of the line:

    first second

Change the first word to ```hello```, but while correcting a typo:

    cehelo<BS>lo<ESC>

Move to the next word and repeat:

    w.

Result is ```hello helolo``` but we expect ```hello hello```

**Comment by jaredpar** [comment]
Hmm, that should work.  I will look into that.

**Comment by jaredpar** [comment]
Pretty sure I understand the problem here.  If you check the current value of the `backspace` setting I'm guessing it doesn't include the `"start"` value.  

The `"start"` value is considered during repeat of insert mode operations and in this particular case VsVim is handling the check incorrectly.  If you add `"start"` to your `_vsvimrc` file this should go away.  

Or if you don't have a `_vsvimrc` change the default settings to gVim 7.4 instead of 7.3.  

- Tools -> Options -> VsVim

**Comment by MartinRykfors** [comment]
Adding ```set backspace=start``` to my .vimrc made the problem go away on my end. Cheers!

**Comment by joshcameron** [comment]
Yes, the workaround above fixes my bug (#1555) as well. Thanks!
