### ISSUE TITLE
cc and indentation not working

### ISSUE THREAD

**Issue by madsystem** [jaredpar/VsVim#1534]
Unfortunately cc does not start at the propper indentation level if the line was empty for example an new line added with o (and then switched directly to normal mode). Here is an gif explaining it a little better.

http://giphy.com/gifs/yoJC2EkaGPvMzsHK36

Im using pure visual studio indentation/tab settings. Changing them to my gvim settings did not help. Any tips, workarounds? Tested languages are c# and c++.

Btw thanks for this really great plugin :)

Cheers, Kris

**Comment by Kantis** [comment]
Use :set autoindent to make cc automatically indent correctly

**Comment by jaredpar** [comment]
@Kantis unfortunately it's not that simple in this case.  The gVim indent behavior works the way it does because it relies on `indentexpr` for this scenario (typically it is set to `GetVimIndent`).  

VsVim doesn't have support for `indentexpr` hence this scenario won't work even with `autoindent`.  

To get this to work both `indentexpr` would need to be supported and some logical implementation of `GetVimIndent` would be needed for C based languages.

**Comment by friedroman** [comment]
I'd also really appreciate this. I also noticed `o` sometimes (rarely though) fails to autoindent. Not when going to normal mode on an empty line, which is expected. Could not spot a pattern so far for a clean repro.
Thanks for the great extension, Jared. It is appreciated.

**Comment by Zantier** [comment]
As a workaround, I put this as a line in my %userprofile%\_vsvimrc

    nnoremap cc ddO

It won't cover other cases involving c, but hopefully that helps.
