### ISSUE TITLE
My statusline gone!

### ISSUE THREAD

**Issue by JoeSchr** [jaredpar/VsVim#1548]
Hi,
first of all, great extension, wouldn't know what to do without it.

BUT suddenly my statusline is gone! I was playing around with Fonts and Colors and some windows setting. Is there anything in Fonts & Colors or a Window or Toolbar or maybe something in the vimrc which changes something about the statusline?

Btw. commands like / and :wq still work

**Comment by JoeSchr** [comment]
Sry, no hassle, I found it! Just had to move around the lower part of the "sub-window" e.g. like Output. Somehow this window was unstucked and therefor I didn't see the bottom of the vsvim window!

Thx for all your work!

**Comment by jaredpar** [comment]
Glad you were able to find it :)

**Comment by slagernate** [comment]
My command margin disappeared and I was unable to use the status bar as well. I tried setting the command margin to false and then back to true, and I also tried closing and reopening some of my windows (Output, Call Hierarchy, etc), to no avail. I read this thread and it still wasn't clear to me how to fix it, so in case anyone else stumbles here: all I had to do was "re-attach" one of my windows to the bottom and my command margin was back. (I didn't realize they weren't attached because they kept opening in the same spot as if they were attached, even though they weren't). Cheers.
