### ISSUE TITLE
VsVim processing the the arrow keys and not letting SQL Prompt access it

### ISSUE THREAD

**Issue by AnuDeshpande** [jaredpar/VsVim#1561]
Our product SQL Prompt: http://www.red-gate.com/products/sql-development/sql-prompt/ is a completion tool and add-in for SQL Server Management Studio and Visual Studio.

One of our customer reported that in Visual Studio (when you have VsVim installed) sql prompt suggestions pop up but when you want to pick one (without using the mouse) the up/down cursors on the keyboard move up/down a line in the file and dismisses the suggestions window instead of selecting a different suggestion. Customer has to use the Mouse to select the item.
After disabling VSVim the issue goes away.

Our developers investigated the issue and it looks like VsVim is processing the arrow keys before they're passed onto us and either using them or passing them directly on to the query window.

Is there anyway this issue can be looked into from your side?

**Comment by timabell** [comment]
That customer was me :-) Cheers for filing the bug @RedgateSupport

**Comment by jaredpar** [comment]
@RedgateSupport  I think I know what is going wrong here.  

In general VsVim is constantly grabbing key strokes and processing them as vim style commands.  But it is designed to step back and let Visual Studio handle keystrokes when it detects that features like Intellisense are currently active.  

The trick though is knowing Intellisense is active.  By default it will use the [ICompletionBroker](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.language.intellisense.icompletionbroker.aspx) interface to accomplish this.  It's the standard interface that Visual Studio uses.    

I'm guessing that SQL Prompt isn't implementing that interface as a part of its completion story.  If so then that would explain the behavior.  VsVim doesn't see Intellisense active so it processes the arrow keys as commands.  

If that is the case I can work around it but I need a small amount of information from you all:

- What is the `GUID` for the `VsPackage` of the tool?  This allows me to only turn on the work around when the package is actually installed.  
- How can I detect programatically that your completion window is active?  

If there is currently no way to do the second one would it be possible for you all to add it?  It could be as simple as putting a `GUID` into the `ITextView` whenever the popup is active.  Basically anything that I can safely query into on every key stroke.

**Comment by RedgateSupport** [comment]
Thanks for the update Jared!

I forwarded your response to our developers and as per that SQL Prompt’s currently an addin rather than an extension which means it doesn’t have a VsPackage guid.

We’ve got some work planned over the next few months to switch to an extension in VS for VS2015 support. So it might be best to revisit this issue then?

Thanks for looking into this and helping us with this issue :)

I will be in touch shortly.

**Comment by jaredpar** [comment]
@RedgateSupport 

Ah didn't realize it was an Add In.  Is there any other item I can query to know if it is installed or not?  Checking the file system, registry, etc ... all are doable.  I default to the VS Package `GUID` because most extensions have one.  

The reason I need this is the code which detects Intellisense is pluggable.  This is for example how I support the various ReSharper versions.  I prefer to only load the work around in question if the product is actually installed.

**Comment by cwitthauer** [comment]
I noticed just now that this is no longer happening. I have SQL Prompt 6.4.1.164 and VsVim 1.8.0.

Not sure on which side it was fixed but thank you!

**Comment by jaredpar** [comment]
Closing due to lack of response here.
