### ISSUE TITLE
Discussion: would it make sense to build in these window mappings?

### ISSUE THREAD

**Issue by Kazark** [jaredpar/VsVim#1569]
Jared, I have these mappings in my `_vsvimrc`:

```
map <C-w>v :vscmd Window.NewVerticalTabGroup<CR>
map <C-w>H :vscmd Window.MovetoPreviousTabGroup<CR>
map <C-w>L :vscmd Window.MovetoNextTabGroup<CR>
```

I know that by doing this I am overriding the current behavior of <kbd>CTRL</kbd>-<kbd>w</kbd> <kbd>v</kbd>, but I never really want to do what it does when I'm in Visual Studio anyway (and if I did I could always `:vs`). Also of course the <kbd>H</kbd> and <kbd>L</kbd> mappings aren't strictly what they do in Vim. My contention, though, is that these are the mappings that make the most sense in light of the VS/Vim window/tab impedance mismatch.

So the question is, would this be helpful another for other people that it would be nice to incorporate it into the core? If the answer is _no_, that's no sweat off my back, I can keep the mappings in my `_vsvimrc`. If the answer is _yes_, I'll submit a pull request.

Thoughts, Jared and other watchers?

**Comment by jaredpar** [comment]
I'm generally shy away from adding default key mappings to VsVim.  Advanced users are highly sensitive to them and any deviation from VS or vim standard usually results in negative feedback.

I have thought in the past about producing a file though which represents a logical vim mapping to Visual Studio commands.  Something new or experimental users could be pointed at.  I think this would fix nicely.

**Comment by Kazark** [comment]
Yeah, perhaps even adding it as a suggestion in the documentation could be enough.

**Comment by tgaldi** [comment]
This is not directly related but is there a way to create a vim command that would either perform a Window.NewVerticalTabGroup or Window.MovetoNextTabGroup if a next tab group already exists?

I generally work with one or two tab groups and I have to use tabjumper to jump between (alt-k).
I also have to have separate keys for NewVerticalTabGroup(alt-;) and MoveNextTabGroup(alt-l).
MovePreviousTabGroup is (alt-h).

I really wish visual studio could be set up similar to emacs using buffers that you open/close/switch between rather than tabs and tab groups.

Sorry to necro an old thread and I know this isn't exactly vsvim related but I haven't found any other discussions on this.

**Comment by ricksladkey** [comment]
Since the window commands have been improved (e.g. `<C-w>H` and <C-w>L`) and since we cannot change the semantics of `<C-w>v` without being incompatible with vim, I think this issue can be closed.
