### ISSUE TITLE
VsVim does not support vimscript function?

### ISSUE THREAD

**Issue by akappel** [jaredpar/VsVim#1573]
Hello Jared, loving the plugin so far. Just now, I placed a function in my _vimrc for smooth scrolling on C-d and C-u. When I attempted the commands, it displayed ":call to function SmoothScroll not supported." I noticed there was a previous issue that discussed functions circa 2013. Is there still no updates in this regard? Here is the actual function by the way:

```VimL
function SmoothScroll(up)
    if a:up
        let scrollaction="\<C-y>"
    else
        let scrollaction="\<C-e>"
    endif
    exec "normal " . scrollaction
    redraw
    let counter=1
    while counter<&scroll
        let counter+=1
        sleep 10m
        redraw
        exec "normal " . scrollaction
    endwhile
endfunction

nnoremap <C-U> :call SmoothScroll(1)<Enter>
nnoremap <C-D> :call SmoothScroll(0)<Enter>
```

As an aside, how hard would it be to implement? I would love to contribute and am currently doing FSharpKoans to get acclimated to the language. If you could point me towards where to start, I can fork and play around with it myself. Thank you!

**Comment by jaredpar** [comment]
At this time functions are still not supported.  Issue #1284 is tracking adding that.  

Adding support for just calling functions is moderately difficult.  The code already supports parsing functions and executing blocks of statements.  Calling functions is mostly just combining those two operations together.  The bulk of the implementation would be inside of Interpreter_Interpreter.fs:

> https://github.com/jaredpar/VsVim/blob/master/Src/VimCore/Interpreter_Interpreter.fs

It hasn't been done at this point because I haven't been actively investing in the vim script support lately.  I've been giving items like motions and such priority.
