### ISSUE TITLE
Exception when copying to clipboard

### ISSUE THREAD

**Issue by kostayScr** [jaredpar/VsVim#1578]
Hello,
I've been using VsVim and I got an exception when doing ```"*yaw```
It looks to be related to VsVim, the ActivityLog.xml - http://pastebin.com/FrJBQXmz.
I can reproduce the error, here is the code snippet:
```cpp
char* GetProcessDEPInfo(HANDLE hProcess){
```
Place the cursor on ```GetProcessDEPInfo```.
It still copies the text just fine.
VsVim version 1.8.0.0 .
I'm sorry if this issue was reported already, I didn't find it while searching in issues.
Thank you so much for your work on this extension, it is very appreciated and useful:)

**Comment by jaredpar** [comment]
Thanks for reporting that!

It is possible for the Windows clipboard to get into a bad state.  When that happens both copy and paste operations can result in exceptions.  It looks like I'm not properly handling that exception in this particular case.  I will fix that so that it doesn't produce a VS error like that.

**Comment by kostayScr** [comment]
I hope I included all the necessary information.
Thank you for working on this wonderful project:)
