### ISSUE TITLE
Cannot input 'P' into watch expression in Dev14

### ISSUE THREAD

**Issue by rcorre** [jaredpar/VsVim#1625]
This is bizarre enough that I'm wondering if I may be crazy, but here goes:

When VsVim is enabled, I can't input the character 'P' into a watch expression while debugging.
I can input a lowercase 'p', as well as any other character I've tried, but capital 'P' is ignored.
This issue goes away if I disable VsVim.

I'm on VS2015 Preview with VsVim `1.8.0.0`.

**Comment by jaredpar** [comment]
> This is bizarre enough that I'm wondering if I may be crazy, but here goes:

No.  In fact I had the same thought when I couldn't use <kbd>P</kbd> on my VS 2015 drop.  I just assumed it was because of my internal setup and constant cycling of non-released dogfood builds.  Hence I've never bothered to investigate it. 

But looks like neither of us is crazy and this is a real bug.  Will look into this.  Have a hunch at what is going wrong.
