### ISSUE TITLE
Disabed VsVim still interferes with typing capital S, C or P

### ISSUE THREAD

**Issue by Predelnik** [jaredpar/VsVim#1654]
I'm not sure that this was discussed before but I think it's slightly disturbing that disabling VsVim with control-shift-f12 results in loss of ability to type capital letters S,C or P because it handles Control,Shift,Alt+SCP by itself, so I have to remap them to Visual Studio in that case.

**Comment by jaredpar** [comment]
@Predelnik thanks for reporting that issue.

What version of VsVim are you using?  I had an issue with the handling of S, C and P before but it should be fixed with the 2.0.0 versions of VsVim.  

Also what window are you seeing that behavior in?  Before it was limited to the locals, watch, etc ... windows.  Are you seeing it elsewhere?

**Comment by Predelnik** [comment]
I'm using the one from Visual Studio Gallery which appears to be 2.0.1.0 and VS2013. For me it happens in normal document editor window, as I've tested in watch and some other windows it works fine.

**Comment by alexhardwicke** [comment]
I'm having a similar issue - I can't type Shift+C or Shift+P in the regular editor with VsVim disabled with Ctrl+Shift+F12, nor in C# interactive at all (regardless of VsVim state). Unlike @Predelnik, I can type Shift+S though.

Space also doesn't work in C# interactive, but it does work in the regular editor window. Shift+Space works in VsVim.

I'd guess that this ticket and https://github.com/jaredpar/VsVim/issues/1713 are related.

VsVim 2.0.1.0, Visual Studio 2015 with Update 1.
