### ISSUE TITLE
VsVim Keyboard Options Missing

### ISSUE THREAD

**Issue by tastephens** [jaredpar/VsVim#1658]
I'm using Visual Studio 2015 Community on Windows 10 Pro, both German. In the past, on Windows 8.1 with VS 2013, VsVim has worked fine. I think it also initially worked after I upgraded to W10 and VS2015 (clean installs). Suddenly today, however, I noticed I'm unable to scroll up and down with Ctrl+U/Ctrl+D. I went to check the keyboard settings, and they're empty:
![vsvimkeyboard](https://cloud.githubusercontent.com/assets/7363295/9277824/da67dd5a-42ac-11e5-8f64-378fb97fb17a.png)
I've tried resetting the keyboard settings, uninstalling/reinstalling VsVim, running VS under a different user account (with completely fresh settings), etc., and the result is always the same.

**Comment by jaredpar** [comment]
Hmm, that's very much unexpected.  Have you run VS 2015 on multiple machines?  I wonder if VS roaming settings could be coming into play here.

**Comment by Farami** [comment]
I had the same issue. What fixed it for me was downloading the Visual Studio 2015 Language Pack and changing the language to english.

Seems to be a localisation problem.

**Comment by jaredpar** [comment]
This is a known issue with Visual Studio when used on multiple machines. Visual Studio sync's all of the key binding changes VsVim makes here but none of the VsVim data. Hence when VsVim starts on the new machine it sees no bindings that are conflicting.

I've reported this to Visual Studio and the behavior is By Design. There are no optionts for me to remove the keys without Visual Studio syncing to other instances tied to the same account.

**Comment by TooManyDots** [comment]
Is there a way to change these keybindings in some file anywhere on disk? I have the same problem, all my options are gone and now ctrl+d opens some file dialog i dont care about and i cant change it to something useful.

**Comment by s3rb31** [comment]
This is a localization problem as @Farami said. I just installed VS2019 freshly with VsVim and had this exact problem. Notably _only_ F2, F6 and F7 would show in the list because the translation is the same for my language. 

I was not signed in in VS and I don't use VS on multiple machines. I tried everything from #2434 and #1658. The only thing that works was installing the English language pack.

Why is this closed? This is a bug and it should be fixed ...

**Comment by jaredpar** [comment]
> This is a localization problem as @Farami said.

Disagree. This is a general problem for which a solution is more complicated due to localization issues.

> Why is this closed? This is a bug and it should be fixed ...

Because I don't see a realistic path to fixing this bug. As I stated above the underlying behavior here is that Visual Studio is deleting all the keyboard information out from under VsVim. There is no way for VsVim to opt out of this or even recover the initial keyboard state. I've pushed on Visual Studio several times to change this behavior but it's not risen to their priority list.

The only way VsVim could fix this is essentially store personal information and sync it between machines in the same way that Visual Studio does (with some complicated localization logic thrown in for kicks). That just doesn't seem very realistic to me.

**Comment by s3rb31** [comment]
I dont understand how it can be a sync problem when I never used VS on multiple machines.

**Comment by s3rb31** [comment]
Hey thanks for the reply! I dont understand how it can be a sync problem when I never used VS on multiple machines. I didn't even log in to said VS installation so how could it sync any settings or key bindings?

Greets

**Comment by s3rb31** [comment]
Hey thanks for the reply! I dont understand how it can be a sync problem when I never used VS on multiple machines. I didn't even log in to said VS installation so how could it sync any settings or key bindings?
