### ISSUE TITLE
VsVim replacing character before caret with > when pressing TAB

### ISSUE THREAD

**Issue by fluffynuts** [jaredpar/VsVim#1669]
Just noticed this tonight, in VS2015, Community Edition. I haven't seen this in my work version of VS2015 Professional. The symptom is that, after a little while of editing, when I press TAB, I get a > replacing the character before the caret. Pressing Ctrl-Shift-F12 to disable VsVim makes this behaviour stop; re-enabling VsVim makes the behaviour emerge again ):

**Comment by fluffynuts** [comment]
Note, I can work around it temporarily with:
imap <tab> <tab>
(or restarting Visual Studio, but that's super-painful)

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue.  Given that the `imap` command can fix it I wonder if there isn't another mapping that is coming into play here.  Possibly because of a difference in the vimrc files between the two machines.  

When that behavior shows up can you run `:imap` (without arguments) to see if there are any errant mappings that could cause this behavior?

**Comment by fluffynuts** [comment]
This issue has been open for ages and I haven't managed to provide more data. Closing.
