### ISSUE TITLE
OpenClipboard Failed

### ISSUE THREAD

**Issue by baskus** [jaredpar/VsVim#1675]
I have this set in my config `set clipboard=unnamed` which causes the windows clipboard to be used for yanks, deletes etc. and that's great for interop between Visual Studio and other apps. However, I get this in my error log

```
  <entry>
    <record>552</record>
    <time>2015/10/09 13:29:56.225</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)&#x000D;&#x000A;   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)&#x000D;&#x000A;   at System.Windows.Clipboard.SetDataInternal(String format, Object data)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text)&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.&lt;&gt;c__DisplayClass4.&lt;SetText&gt;b__3()&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.TryAccessClipboard(Action action, Int32 retryCount, Int32 pauseMilliseconds)</description>
  </entry>
```

and after I get it, everything that affects the clipboard (i.e. basically all of vim), takes several seconds to complete. This makes editing horrible!

I think there is some information on how to approach this here:

[http://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid#](http://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid#)

**Comment by jaredpar** [comment]
Thanks for reporting.

Unfortunately this error is "by design of Windows".  The clipboard in Windows is a shared resource that has no synchronization capabilities.  Hence every time an application uses the clipboard it is racing with any other application that is also doing so.  

VsVim carefully guards use of the clipboard and catches exceptions that would result from it.  Unfortunately when an exception happens there is no way to recover.  It's just a notification that the clipboard is in a state where it can't be used.  

The reason there is an error in the VS log is I made the intentional decision to put it in there.  I thought it was better to add an entry to the error log vs. failing silently in this case.  Wish there was more I could do here.

**Comment by baskus** [comment]
Oh, that's unfortuante. :( Nice of you to log it though.

Is there any way to make it not lag when the clipboard fails? Could VsVim notify me more clearly?

**Comment by jaredpar** [comment]
@baskus i've been thinking about adding an option here to silently ignore this failure and not retry on error. It would be off by default but available to people who hit this problem.

**Comment by arteny** [comment]
Error dialog still apears for this error in VS2017
