### ISSUE TITLE
'Handle all with VsVim' does not change all bindings

### ISSUE THREAD

**Issue by rcorre** [jaredpar/VsVim#1677]
In `Options > VsVim > Keyboard`, 'Handle all with VsVim' leaves some mappings to Visual Studio even if there is a valid Vim mapping.

For example, `<c-a>` gets left behind even though it has a default VsVim binding (numeric increment).

**Comment by jaredpar** [comment]
Thanks for reporting. 

The behavior of leaving <kbd>Ctrl+A</kdg>, <kbd>Ctrl+X</kbd> and <kbd>Ctrl+C</kbd.> as controlled by Visual Studio is by design.  Initially I had "Handle all with VsVim" change everything but I ended up getting a lot of negative feedback about that change.  Many people wanted to keep the standard copy, paste and cut commands to Windows standard ones.  Hence I ended up with this behavior.
