### ISSUE TITLE
Implement globpath

### ISSUE THREAD

**Issue by dawikur** [jaredpar/VsVim#1687]
In my vimrc I am using globpath combined with split to load settings

```vimL
for b:fpath in split(globpath(b:vimsettings, '*.vim'), '\n')
  exe 'source' b:fpath
endfor
```

VsVim isn't handling them and this makes my vimrc completely useless.

**Comment by jaredpar** [comment]
Implementing `globpath` alone wouldn't allow for this to start working though.  It would require additionally implementing `split`, `for ... in` and `exe` ...  

The VsVim support for vimscript is pretty limited and meant only for simple vimrc files and common edit commands like `substitute`.  Full vimscript support isn't an actual goal, mostly because it's a very large undertaking.  

In general the best way to handle this is to have a .vsvimrc file which contains the settings that VsVim supports.  VsVim will prefer this over a vimrc file.

**Comment by dawikur** [comment]
Yeah, I thought that not only `globpath` isn't supported but didn't want to create issue for each one - simple globpath is first operation that fails.

Absence of `for`, `in`, `split` and `globpath` can be workarounded with script that will *unroll* `for`, but *inlining* all sources   breaks pretty badly concept of having dotfiles on github.

**Comment by dawikur** [comment]
OK, I have workaround for this issue with simple plugin
https://github.com/dawikur/simplifyRC.vim

When I save vimrc (or other *.vim) file it generates _vsvimrc with inlined source files.

Closing.
