### ISSUE TITLE
Quick <ESC>+o  in Insert mode puts cursor on next line in normal mode

### ISSUE THREAD

**Issue by jakobbotsch** [jaredpar/VsVim#1762]
I sometimes see a small problem when doing <kbd>ESC</kbd><kbd>o</kbd> while in Insert mode. VsVim will put me on the next line, but in normal mode instead of the expected insert mode; I can easily reproduce this if I press the keys in rapid succession. If I leave a small delay between <kbd>ESC</kbd> and <kbd>o</kbd> VsVim will correctly leave me in insert mode on the next line.

**Comment by ricksladkey** [comment]
I have been having a similar symptom recently that I haven't been able to quite reproduce at will.  I have a idiomatic sequence I often type rapidly after finishing text in insert mode: <kbd>Esc</kbd> <kbd>:</kbd> <kbd>w </kbd> <kbd>Enter</kbd>, which instead of entering normal mode and writing the buffer, inserts a newline into the buffer.

**Comment by jaredpar** [comment]
Sorry I'm unable to reproduce this.

**Comment by jakobbotsch** [comment]
I just retested, and it does appear to be fixed for me as well.
