### ISSUE TITLE
Cant :vsp in a .html

### ISSUE THREAD

**Issue by gsvolt** [jaredpar/VsVim#1779]
Editing a .html, the :vsp (visual split vertical) does not seem to work.
It does work on .js files, .cs files.. just not on .html
Thought I'd invite comments from other users to see if others see the same outcome. If so, perhaps would be nice to implement this in vsvim

When I do issue :vsp, the message in VsVim's command bar down below is: 
Command "Window.NewWindow" is not available.

**Comment by joshiji** [comment]
I am also seeing this issue. I am facing it in asp.net mvc's .cshtml files.

**Comment by jaredpar** [comment]
This appears to be a limitation in the cshtml / html editor.  VsVim doesn't really implement vertical split, it just asks Visual Studio to create one.  In the cases this error presents it's because the underlying editor / environment doesn't support it.  Unfortunately nothing I can do to override this.
