### ISSUE TITLE
Support for autocmd events "FileType" and "BufWritePre"

### ISSUE THREAD

**Issue by WillemMali** [jaredpar/VsVim#1783]
Hi,

As you said you'd consider implementing specific `autocmd` events on request, I'd like to ask you to implement these two:

```
autocmd FileType
autocmd BufWritePre (and BufWrite, they do the same thing)
```

I usually use `FileType` quite extensively (for per-filetype settings i.e. indentation) and I use `BufWritePre` for making modifications to my current file just before changes are saved to disk (for formatting, mostly).

Docs on both commands:

http://vimdoc.sourceforge.net/htmldoc/autocmd.html#BufWriteCmd
http://vimdoc.sourceforge.net/htmldoc/filetype.html#filetypes

The line in my `.vimrc` that made me request this feature:
`autocmd FileType cs,xaml autocmd BufWritePre <buffer> :%s/\s\+$//e`

(It removes trailing spaces for C# and XAML files.)

Thank you for your time!

**Comment by jaredpar** [comment]
Thanks for the suggestion.

I've considered adding this but `autocmd` support in its current form is limited because I don't support functions.  Pretty much all of the `autocmd` samples users sent me included functions and hence I haven't put a lot of further work into this feature.  If I pick it back up though I'll consider this request.

**Comment by jaredpar** [comment]
Decided against adding further autocmd support here.
