### ISSUE TITLE
VsVim temporary disable breaks cursor

### ISSUE THREAD

**Issue by elrob** [jaredpar/VsVim#1791]
- ctrl + shift + F12 to disable VsVim temporarily (temporarily only - not disabling the extension completely that requires a restart)
- try to move the cursor to the end of the line and it doesn't work
- cursor can only reach the character before the end of the line

The temporary disable functionality is vital for me as I pair-program and often my partner can not use VIM. We need to be able to switch VSVim off and on quickly (without a restart). We've all now had to completely disable VSVim which makes me sad. I love the plug-in otherwise.

This issue has already been mentioned on the Q&A: https://visualstudiogallery.msdn.microsoft.com/59ca71b3-a4a3-46ca-8fe1-0e90e3f79329

**Comment by jaredpar** [comment]
Thanks for reporting this issue.  I'm pretty sure I know what the issue here is and is similar to a bug I just fixed yesterday.

**Comment by jaredpar** [comment]
This bug is fixed now.  If you wait for AppVeyor to complete it's run you can grab a build with the fix off of vsixgallery.com.

**Comment by raztus** [comment]
I'm in the same scenario (pair-programming) and this was an ugly issue. Just installed the latest version from vsixgallery.com, and it fixes the issue. Thanks, @jaredpar!

**Comment by jaredpar** [comment]
Yeah that particular function has been responsible for no less than 3 bugs in the 2.1.0 release.  Didn't quite realize all the ramifications that fix would have on selection.  Getting educated quickly 😄

**Comment by MartinL0815** [comment]
Sorry, but the issue even occurs without disabling VsVim!

Another extension "Entrian Source Search" uses the VS API to get word boundaries and is since updating VsVim not always anymore to get a word at the end of a line for sourch pattern creation.

My observed problematic lines match the RE:

    ^\s+\w+$

If "Entrian Source Search" is triggered to use the word under the caret for the next search it retrieves the first RE group:

    ^\s+(\w+)\w$

So it misses the last character.

I disabled VsVim to see, if the last update causes the problem and even now selecting the text in such a line from Pos1 to End misses the last character of the line.
This character cannot be selected with VsVim being disabled.

As Jared stated the bug is already fixed and the fix should be available, right?

Does this fix includes this described buggy behavior?

**Comment by jaredpar** [comment]
@MartinL0815 it's likely the latest version fixes this problem.  You can install it manually from this location to test out:

http://vsixgallery.com/extension/VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3/

Going to be releasing a new version to the official gallery in a day or two.
