### ISSUE TITLE
VsVim is disabled every time I start up VS

### ISSUE THREAD

**Issue by deevus** [jaredpar/VsVim#1804]
I have to go into Extensions and enable it, then restart Visual Studio. 

Any ideas as to why this would be happening?

**Comment by jacres** [comment]
Same happening here - this began happening within the past month or so.

**Comment by jaredpar** [comment]
I've seen this behavior before myself on a short term basis on one of my machines.  I always assumed that because of all of the extension work I do I had somehow gotten Visual Studio in a bit of a corrupted state.  Based on this though it seems to just be an issue with Visual Studio itself.  

Unfortunately though this is not anything that I control.  This is controlled by Visual Studio itself and hence I can't really do anything to fix this.  I will follow up internally though, see if this is known problem, and potentially how to work around it.

**Comment by DavidFeng** [comment]
Same was happening, too.

thanks @jacres !  it works for me to

**Comment by mikehadlow** [comment]
This happened to me too. I followed @jacres advice and uninstalled VsVIM and restarted. I had to do this twice before it finally disappeared. It's working fine now. Thanks!

Note that my first attempt failed because I stupidly had another instance of VS open at the same time.
