### ISSUE TITLE
VsVim gets disabled after restarting Visual Studio for the second time

### ISSUE THREAD

**Issue by rgeorgiev583** [jaredpar/VsVim#1807]
After enabling VsVim, Visual Studio requests a restart of the environment.  I follow that instruction (explicitly via the **Restart Now** button which appears in the **Extensions and Updates** dialog, or either the extension won't get enabled), and VsVim is enabled and works for the current instance of the IDE.  However, when I close Visual Studio and start it again, VsVim gets disabled for no apparent reason at all without me explicitly disabling it.
I tried setting the **VimRc File Loading** option first to **vsvimrc files only**, then to **No vsvimrc or vimrc files** on the suggestion of a friend who uses VsVim, yet neither of these changes could fix my problem.
And suggestions or ideas for coping with this?

**Comment by cice** [comment]
i have the exact problem since i updated VS2015 to Update3 yesterday. Really annoying.

**Comment by jaredpar** [comment]
I've heard a few reports of this but haven't been able to track down the behavior myself.  I asked around the Visual Studio team and they said this could occur if VsVim is throwing an unhandled exception.  This can result in an extension being disabled because it's deemed to be unreliable. 

It's possible that is what's happening here but given that I can't produce it locally I can't see what is failing.  If possible could you check two items:

1. The activity log which is located at: `%AppData%\Microsoft\VisualStudio\14.0\ActivityLog.XML`
2. Start Visual Studio under a debugger and see what VsVim is throwing

If VsVim is throwing an exception it should be visible using either of these tactics.  Once I know what the problem is I can work around it.

**Comment by jaredpar** [comment]
Also have you taken a look at #1804?

**Comment by cice** [comment]
@jaredpar thanks, seems to be the same issue as #1804, i will try jacres solution and report back

**Comment by cice** [comment]
https://github.com/jaredpar/VsVim/issues/1804#issuecomment-230495041 this solution worked for me too. i had to uninstall vsvim several times. after re-installing, its now working smoothly.

**Comment by rgeorgiev583** [comment]
Thanks a lot to everyone: the solution in #1804 fixed my problem.  I think the issue can already be closed now.
