### ISSUE TITLE
Switch to insert mode using a command

### ISSUE THREAD

**Issue by mgutekunst** [jaredpar/VsVim#1825]
Hi, 

when I'm in normal mode is there a command to switch to insert mode? 
Something like ` :Insert-mode` ?

**Comment by cbates-** [comment]
I must misunderstand the question, because there are a lot of single keystrokes that switch to insert mode: i, shift-I, o, shift-o, a, shift-a, etc.
Perhaps you mean when you are at the ':' prompt?  If there are no characters on the command line, <backspace> takes you back to normal mode, where i, a, o, etc. work.
(Of course, <Esc> generally takes you immediately from command or insert mode to normal mode.)

**Comment by mgutekunst** [comment]
Sorry, I should have been more specific: 

I contributed to the AceJump Visual Studio plugin ( repo is here: https://github.com/jsturtevant/ace-jump ). I put a Command around that logic so that you can now bind the invocation to an arbitrary key. 

In my case, I wanted to map it  <Space> in normal mode which works perfect. The strange thing is that the character i type after invocation isn't forwarded to AceJump. But if i switch to insert mode (either before or after invoking the AceJump command) the command recognizes the character I type. 

I thought I could work around that problem by programmatically switching to insert mode after I invoke AceJump by hitting <Space> but I couldn't find the command to do that. So what I'm looking for is something like `:vsc InvokeAceJumpCommand | "Insert command to switch to insert mode here" `

**Comment by jaredpar** [comment]
Gotcha.  The reason you see this different behavior for normal / insert mode is the basic philosophy of VsVim.  

- Normal mode: developer is using Vim.  Control the keyboard and treat every key stroke as a Vim command.
- Insert mode: developer is writing code. In cases where keyboard is unambiguously a Vim command then treat as Vim command.  Otherwise just hand off the key stroke to Visual Studio and let it take over.  

Have you considered disabling VsVim while Ace Jump is processing keystrokes?  VsVim registers the commands `VsVim.SetDisabled` and `VsVim.SetEnabled`.

**Comment by cbates-** [comment]
> VsVim registers the commands VsVim.SetDisabled and VsVim.SetEnabled.
Could we please get a VsVim.SetNormalMode command?  See: https://github.com/jaredpar/VsVim/issues/741

**Comment by mgutekunst** [comment]
> Have you considered disabling VsVim while Ace Jump is processing keystrokes? VsVim registers the commands VsVim.SetDisabled and VsVim.SetEnabled. 

No, not yet. I wasn't aware of these commands. 

> (And, btw, how do you access registered commands from inside an extension?)
I don't know that either, but there should be a way to do this. I hope so at least

**Comment by jaredpar** [comment]
@cbates- 

> Could we please get a VsVim.SetNormalMode command? See: #741

Working on that.  Decided to have a general `VsVim.SetMode` command.  Have the code implemented but need to figure out why parameters aren't being fully passed to the Exec method. 

https://github.com/jaredpar/VsVim/commit/76a687f4677c90e7c515a4f85bb29c2307a04194

Have an email thread out to the VS platform guys.  Once that's resolved this will get merged in. 

@mgutekunst 

> I don't know that either, but there should be a way to do this. I hope so at least.

To execute the commands use [Dte.ExecuteCommand](https://msdn.microsoft.com/en-us/library/envdte._dte.executecommand.aspx?f=255&MSPPError=-2147217396).   Here is an example where [VsVim uses it](https://github.com/jaredpar/VsVim/blob/master/Src/VsVimShared/VsVimHost.cs#L227)

**Comment by mgutekunst** [comment]
@jaredpar Thanks. Works as expected now. The only flaw is that I don't have the `VsVim.SetEnabled` and `VsVim.SetDisabled` commands but only `VsVim.ToggleEnabled`. Jumping works with this command as well but if VsVim is disabled before I call aceJump, things might get messed up. 

So I'll probably switch to your `VsVim.SetMode` command once this is done. Do you also provide a `VsVim.GetMode` command?

**Comment by jaredpar** [comment]
@mgutekunst 

> So I'll probably switch to your VsVim.SetMode command once this is done. Do you also provide a VsVim.GetMode command?

Should be easy enough.  Probably both print it out to the command window and add it to the `pVariantOut` parameter.

**Comment by skeept** [comment]
I think vim has a :startinsert command...

**Comment by cbates-** [comment]
Thank you!
