### ISSUE TITLE
Split navigation broken in diff view

### ISSUE THREAD

**Issue by rcorre** [jaredpar/VsVim#1836]
Select a commit from the TeamExplorer History view and select `Compare with previous`. This opens a split diff view, but the `<ctrl-w>*` shortcuts for navigating between splits don't work.

**Comment by jaredpar** [comment]
Thanks for reproting.  I will take a look at this.  Likely because it's doing an in window split vs. using the standard VS splitting architecture.

**Comment by ricksladkey** [comment]
I looked into this and there are definitely two text views, and even a third zero-width text view. They are both tightly linked, for coordinated scrolling and shared scroll bar. Our reliance on the window splitting to tell us about multiple windows was therefore flawed, and it other ways as well. For example, `<C-w><C-j>` could only move among splits, not between two vertically stacked tab rows.

My PR #2228 works correctly in all these scenarios and does it without paying any attention to splitting by working directly with the individual text views, which we already fully support. For example, each half of a diff view already has its own command margin. So all we care about is that the text views we already know about are next to each other.

After testing vim, I finally understood the algorithm it uses for 'go to window'. Take `<C-w>h` for example. It draws an imaginary horizontal line from the caret in the current window to the left edge of the screen. Any text views that it intersects are candidates for moving the focus left.

For us to make this work, we only need to calculate the screen rectangles of the text views we are already working with in order to faithfully mimic vim window motions.

**Comment by marza91** [comment]
Hey, getting a fix for this sounds great, thank you :smile: I recently found out that a built-in VS shortcut is "CTRL-|,CTRL-TAB" which does the job, but is a bit irritating to have two different shortcuts for the same thing.

A note on the text view, could it be the "combined view" when looking at merge conflicts? Can't force a conflict right now to illustrate, but I get a window split like this when merging:
```
|-------------------------------------|
|     Server      |     Local         |
|-------------------------------------|
|     Combined after merge            |
|-------------------------------------|

```

Switching to the combined view would probably be good as well (it might already work that way?), but I wouldn't need it personally.

I'm not a VsVim developer, just thought I'd share my experience, thoughts. I can try to test the PR later if that would be of help!
