### ISSUE TITLE
:qa closing visual studio

### ISSUE THREAD

**Issue by IvanNazarov** [jaredpar/VsVim#1841]
Sorry for my bad  english.
Visual studio 2015,  :qa command completely closes the IDE, but must close open tabs.

**Comment by christianrondeau** [comment]
I tend to agree, so here are some additional details on my thoughts.

In Vim, `:q` and `:qa` is expected to quit the software, since there is no overarching concept of "opened project", it's really just a collection of buffers. It could be argued that we can "simply" do `:%bdelete` (or sequential `:bd`) to close files without exiting Visual Studio, but:

1. The "cost" of starting Visual Studio is much higher than starting Vim
2. In Vim, exiting usually means "going back to the shell", where as in Visual Studio, it just means "exit Visual Studio"
3. Even though it's not a buffer, Visual Studio has a project opened, so `:qa` closes all files, but not "everything" per se

So even though the current implementation of `:qa` makes sense, I believe the "close all tabs" approach to be superior.

**Comment by jaredpar** [comment]
Thanks for the feedback here.

This is a subject I've gotten a bit of feedback about.  Informally asking users the preference has been to keep the <kbd>:qa</kbd> behavior in line with vim and have it quit Visual Studio.

**Comment by IvanNazarov** [comment]
may be make :qa behavior optional? Add as option in preferences?

**Comment by cbates-** [comment]
Isn't there a way in vim to execute a command across all windows?  Perhaps that capability combined with bd would do what trick.

**Comment by christianrondeau** [comment]
Like `%bd`…?  :)

**Comment by cbates-** [comment]
@christianrondeau   That's the one, although bd isn't supported, and I doubt '%' is ...

**Comment by hunterxueMS** [comment]
:qa should be close all tabs. It's so annoying to close the application by accident. At least, we should get a chance to configue the behavior in the settings.
