### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by haolly** [jaredpar/VsVim#1891]
![image](https://cloud.githubusercontent.com/assets/2383231/21536916/0c2735d6-cdc4-11e6-800f-830e73fdd363.png)

It happed when I use command `dd`

**Comment by jaredpar** [comment]
Thanks for reporting.  What is happening there is you have the yank / delete operation set to update the system clipboard.  For some reason the system clipboard is in a bad state and is basically throwing errors whenever VsVim tries to access it.  

There isn't much I can do about making the clipboard work.  If it's in a bad state, which can happen, then it can't be fixed by VsVim.  But I can change this into a warning vs. an unhandled exception.

**Comment by zolem** [comment]
I have this same issue. It seems to happen though even when I am not yanking or deleting. Sometimes when I open a new file and just attempt to do anything visual studio will hang for about 5-10 seconds and then throw the alert message telling me this error happened and then everything works great. It gets kind of annoying sometimes.

**Comment by jaredpar** [comment]
This should be fixed now that all WPF clipboard operations are protected.
