### ISSUE TITLE
Definition of \u varies based on 'ignorecase'

### ISSUE THREAD

**Issue by DJMcMayhem** [jaredpar/VsVim#1932]
If I

    :set ignorecase

then

    /\u

will match any letter, upper or lowercase. Once I turn off 'ignorecase', it only matches uppercase characters. I don't think this behavior is standard, because I tried it in real vim, and the setting of 'ignorecase' has no bearing on `\u`.

**Comment by jaredpar** [comment]
Thanks for reporting.  Sounds like there may be a precedence issue here.

**Comment by jaredpar** [comment]
Thanks for filing this.  I've looked into this a bit. I agree with your assertion that standard vim behavior is to treat `\u` as case sensitive even if `ignorecase` is enabled. Unfortunately fixing this appears to be outside the scope of this project.

Under the hood all vim patterns are represented as .NET regex expressions. To properly match `\u` with `ignorecase` enabled a regex engine must able to assign case sensitivity to different portions of the pattern. That's not really possible with a .NET regex. It only has a single option that covers the entirety of the regex. 

In order to fix this I'd essentially need to write a new regex engine. That's beyond the scope of VsVim at this time.
