### ISSUE TITLE
Change color of block caret.

### ISSUE THREAD

**Issue by kkorus** [jaredpar/VsVim#1945]
Hello,
Change color of "block caret" is not the same that I have set to. For example I want my color of block caret to be 255 ; 204 ; 0 but in editor ends up being 179 ; 146 ; 13.

The color I have setup:
![image](https://cloud.githubusercontent.com/assets/2054009/25066147/00a5e6d4-2216-11e7-8b72-6a7fe54cb813.png)

The color in editor (little bit darker):
![image](https://cloud.githubusercontent.com/assets/2054009/25066148/16f028b4-2216-11e7-96bc-8e3c1aa55131.png)

Does anyone have the same issue? Does anyone know how to fix it? 
edit: I think it's because caret is somehow transparent ¯\_(ツ)_/¯
Can this transparency be disabled?

**Comment by michaelHL** [comment]
+1. 😞
It seems like green when I set the color to be yellow(255,255,0)

**Comment by ricksladkey** [comment]
The default caret opacity is 65% and so the color you see is roughly two thirds that color and one third whatever the background color of the character under the cursor is. To get exactly your specified caret color, you can set the opacity to 100% in `.vsvimrc` with `:set vsvimcaret=100`.

The benefit to having the opacity lower than 100% is that the caret color is different from but related to whatever the background color is, which is presumably less jarring. For example, you can try setting a breakpoint (which on my system makes the text background a sort of brick red) and then positioning the caret on that line.

Unfortunately, it is currently impossible to change the color of the text under the cursor, so it quite difficult to get good contrast both within the caret and between the caret and the document. The traditional solution to this problem is the so-called "reverse video" where the foreground and background are swapped. The solution in gvim is that it allows you to set both the foreground and background of the block cursor as can be seen here (with `:colorscheme desert`):

![image](https://user-images.githubusercontent.com/2680524/40879102-265eb20a-6669-11e8-9dea-9b637e58077f.png)

If the cursor foreground color were white in this image, the caret would be extremely hard to read, which is the current situation with VsVim:

![image](https://user-images.githubusercontent.com/2680524/40879143-8b6f10a4-6669-11e8-8e9f-86c271fda055.png)

**Comment by kkorus** [comment]
@ricksladkey Nice, for explanation. 

You said that `currently impossible to change the color of the text under the cursor`. Is it because of Visual Studio of you think it can be done in plugin itself? Cheers.

**Comment by ricksladkey** [comment]
@kkorus I believe it is a limitation in VsVim. Yet, it is an area I've wanted to look into, so I'll take a look at how hard it would be.

**Comment by ricksladkey** [comment]
This issue would be resolved if issue #749 were implemented and the then default opacity was set to 100%.

**Comment by ricksladkey** [comment]
I have a working prototype that allows user-configurable block caret text foreground and background color. Here it is in action editing VsVim itself. The options:

![image](https://user-images.githubusercontent.com/2680524/40943768-5a6e9264-6820-11e8-94da-e1a313c9a196.png)

The results:

![image](https://user-images.githubusercontent.com/2680524/40943683-0da1a462-6820-11e8-8dfb-662a2917403d.png)

I'll test it out locally for a few days and if I don't see any problems, I'll submit a PR.

**Comment by kkorus** [comment]
@ricksladkey Awesome news! Waiting for release.
