### ISSUE TITLE
F#: Escape from edit mode does not work

### ISSUE THREAD

**Issue by munik** [jaredpar/VsVim#1949]
When using the F# editor in Visual Studio 2017 with VsVim, it does not work when I press the Esc key to return from insert mode to normal mode. It works correctly from the C# editor.

Unfortunately, this issue doesn't occur right away. I haven't figured out what triggers it, but once it is triggered, Esc does not work until I restart Visual Studio.

**Comment by jaredpar** [comment]
Sorry for the delay in seeing this.  

I use F# pretty regularly in VS 2017 and haven't seen this issue yet.  Do you have any other extensions installed?  It's possible they are conflicting here.

**Comment by daz10000** [comment]
This just stared happening for me today.  I have even uninstalled and reinstalled vsvim into vs2017.   I insert,  type a few characters,  hit escape and then try a cursor move jhjkl etc and it just types the letters because it's stuck in insert mode.  Maybe an interaction with another plugin that is capturing the escape key?  I hadn't changed anything in visual studio when this happened.

**Comment by daz10000** [comment]
And just as quickly disappeared.   I was playing with the insert mode and function key on keypad - that might have been what unstuck it.  Was also looking through the diagnostics on the about menu.  Have no idea of any of that made a difference but the problem was fairly persistent till just now

**Comment by jaredpar** [comment]
I think this was very lilkely another symptom of the escape bug I just fixed. It most often presented in Visual Mode but could present in other modes as well given the right circumstances. If it shows up again in recent builds though we'll take a deeper look.
