### ISSUE TITLE
No way to switch keyboard shortcuts in VS2015 Pro

### ISSUE THREAD

**Issue by kerskuchen** [jaredpar/VsVim#2013]
Hey!

At work I cannot change the keyboard shortcuts as the menu is empty: 
![vsvim](https://user-images.githubusercontent.com/2393859/31704745-ffa89e70-b3e2-11e7-9268-15cd3c79e8e9.PNG)

We have the following version of VS:
![vsversion](https://user-images.githubusercontent.com/2393859/31704747-02456b68-b3e3-11e7-9d80-266c79e1877b.PNG)

I tried with the current VSVim version of the VS Gallery as well as the latest debug build from Github.
At home it works like a charm with VS2015 Community and VS2017 Community.

**Comment by jaredpar** [comment]
Unfortunately this is the "by design" behavior of Visual Studio. When VsVim unmaps Visual Studio keys, Visual Studio will "helpfull" roam that setting. The result is when you open up VsVim on a diff machine the unset keys have roamed but VsVim doesn't have any information about what keys it unset since it did it on another machine.

There isn't a lot I can do here unfortuantely because 

- VsVim can't roam settings
- Can't ask Visual Studio to not roam the key mapping. 

😦

**Comment by kerskuchen** [comment]
Hey Jared thank you for your response! 😄 

I don't really think roaming settings are a culprit here (or I still do not understand what they mean sorry). I did a new clean install of VS2015 on a new computer at the workplace and then installed VsVim. I did not copy any settings from any VS to this machine. This happened on a fresh install.

I forgot to mention that this is a Windows 7 Pro machine.

**Comment by jaredpar** [comment]
> I did not copy any settings from any VS to this machine.

Did you sign into VS with the same credentials on both machines?

**Comment by kerskuchen** [comment]
The VS2015 at work did not asked me to sign in. At home I am signed in. I will double check tomorrow when I'm back at work.
