### ISSUE TITLE
`gj` and `gk` are off

### ISSUE THREAD

**Issue by 333fred** [jaredpar/VsVim#2060]
When pressing `gj` on a visually-wrapped line, instead of moving directly down one line, the cursor moves down 1 line and over to the right 10 characters. Pressing `gj` again to leave the wrapped line moves down 1 line and back to the original column. Repro seems pretty consistent for me on 27307.0. I've attached my text editor settings, in case there's something going on with my particular settings that's causing the issue. (Rename to .vssettings after downloading, as I can't upload a file ending in .vssettings.)
[vsvim_bug.txt](https://github.com/jaredpar/VsVim/files/1616792/vsvim_bug.txt)

**Comment by jaredpar** [comment]
Not seeing this on my machine. I created a txt file, added an extremely long sentence and was able to `gj` and `gk` around as expected. 

What is the output of `:set`?

**Comment by 333fred** [comment]
```
vimrc="C:\Users\frsilb\.vimrc"
vimrcpaths="C:\Users\frsilb;C:\Users\frsilb\vimfiles;C:\Users\frsilb"
novsvim_cleanmacros
expandtab
number
shiftwidth=4
tabstop=4
```

**Comment by 333fred** [comment]
.vimrc is very simple:
```
nmap ; :
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
```

**Comment by 333fred** [comment]
I tried opening a text file as well, I'm seeing a 2 character jump there.

**Comment by jaredpar** [comment]
@333fred and I debugged locally. It looks like there is a VS feature interfering here (or possible an extension). Appears an adornment is causing the wrapped text to visually shift right in the editor without affecting any of the actual line / column information in the API. This is why VsVim jumps to the right. It's using the correct offsets, the adornment is just shifting the visual view. 

Working with VS team to figure out what is going on here so VsVim can respond appropriately.

**Comment by jaredpar** [comment]
Editor bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/549825

**Comment by ricksladkey** [comment]
I noticed this bug too.

This is a feature of Visual Studio 2013+ where when linewrap is enabled, lines which are indented have their wrapped portions "cuddled" under the text. I believe it was first made popular by Sublime Text and then imitated by Visual Studio and many other editors. The purpose is to keep the "business end of the line" visually adjacent.

I am guessing that @jaredpar does not use linewrap, but I certainly do!  This feature is not a bug, is quite intentional, and is quite popular (with those who use linewrap). However, unfortunately, it interferes with VsVim's attempt to move to the correct column. The good news is that the text lines API definitely encodes all the necessary information to do it correctly.

**Comment by jaredpar** [comment]
> I am guessing that @jaredpar does not use linewrap, but I certainly do! 

Line wrap is evil 😉 

> The good news is that the text lines API definitely encodes all the necessary information to do it correctly.

That's good to know. I hadn't looked at this deeply yet but at a glance I couldn't figure out where to get this. Seems like the PR has it figured out though 😄
