### ISSUE TITLE
Macro search forward and backward

### ISSUE THREAD

**Issue by urbpeti** [jaredpar/VsVim#2077]
If you have an xlm like text. You have two elements and you are in the second element's row. If you record a macro "/>?<" (first search to the tag's end, then search backwards to the tag's start). It's OK, but when you play the macro in new elements the cursor will be at the first element tag's start and not the second elmenet.

**Comment by urbpeti** [comment]
Macros and searches working really bad. This is a very important feature. If you want to make a longer macro, then it jumps bad positions. If I write out the register I do not see my searching term. Maybe this is the problem.

**Comment by jaredpar** [comment]
Sorry you're seeing issues here. Can you try elaborating a bit on the problem here? Perhaps some sample text with a macro that is misbehaving? 

One thing to try is enabling clean Macro recording:

- Tools -> Options -> VsVim
- Change "Clean Macro Recording" to True

When this is set VsVim will attempt to disable all of the VS features that tend to get in the way of macro recording / playback. In particular it will disable Intellisense.

**Comment by urbpeti** [comment]
This option did not help me. 
This is an example for this bug.
If you have a html file, and you want to write a macro for search the tag name and put it above in a html comment.
From this:
``` html
<div tag1="something"
     name="divname">
</div>
```
To this:
``` html
<!-- divname -->
<div tag1="something"
     name="divname">
</div>
```
And the keys what I press for the macro are: `qq/name<CR>f"lyiw?<<CR>O<ESC>i<!-- <ESC>pA --><ESC>q`

In Vim it works perfectly, but in VsVim it works strange. Please check it.

**Comment by jaredpar** [comment]
Thanks for the repro. Will look into that.

At a glance though I'm guessing HTML completion is a problem here. The IDE is pretty agressive with trying to complete matching items like braces, tags, etc ... They can get in the way of VsVim doing macro operations.
