### ISSUE TITLE
Search forward in two macros conflict

### ISSUE THREAD

**Issue by tulsileathers** [jaredpar/VsVim#2115]
Consider this snippet
```
<tr>
            <td width="25%">@Caption("Planned Date")</td>
            <td width="25%">@Text("")</td>
            <td width="25%">@Caption("Manager")</td>
            <td width="25%">@Text("")</td>
</tr>
```
I record two macros one to target the "P" and remove "Planned Date", one to target the "M" and replace "Manager", "/P c2w" and "/M cw" respectively. What I find is that when performing the macro, VsVim doesn't correctly remember the search term but instead repeats the last search. So if I search /P before executing the macros, then the macros function as "/P c2w" and "/P cw" and same if I search for /M. Let me know if there's anything else I could test for you. You should be able to reproduce with the snippet above,.

**Comment by tulsileathers** [comment]
Also I have tried with "Clean Macro recording" set to true in VS options

**Comment by Deadairx** [comment]
I ran into this issue as well last night. Here are some reproduction steps I came up with if it will help.
### C# Snippit
```cs
namespace FooBar
{
	class Program
	{
		static void Main(string[] args)
		{
			string red = "Red";
			string green = "Green";
			string blue = "Blue";
		}
	}
}
```
### Reproduction Steps
|`Clean Macro Recording` | `true`|
|---|---|

First, create macro "h" to search for "red" `qh/red<esc>q`.  
Then return to top `gg` and run the macro `@h`. It will jump to `red` as expected.  
Next, create macro "t" to search for "green" `qt/green<esc>q`.  
Return to top `gg` and run first macro `@h`. It will jump to `green` instead of `red`.  
Return to top `gg` and search for "blue" `/blue`.  
Return to top `gg` and run first macro `@h`. It will jump to `blue` instead of `red`.

### More Info
It seem that Macro recording in VsVim does not perserve what is searched.
When I run `:reg h` it will display as `"h   /`  
When I create this macro in gVim and run `:reg h` it will display as `"h   /red ^M`

**Comment by ricksladkey** [comment]
I've looked into this and nothing typed into the command margin (now that it gets the focus) gets recorded. The command margin getting the focus was a good thing, but this is fallout that needs to be fixed. I'll take a look at it.
