### ISSUE TITLE
Mapping multiple modifiers doesn't work

### ISSUE THREAD

**Issue by Widgertius** [jaredpar/VsVim#2143]
Hello,

So i tried to map something like this..

`map <c-a-k> 64<up>zz`

but this makes my key 'k' get mapped to 

> 64<up>zz

 instead .. am i doing something wrong?

**Comment by ricksladkey** [comment]
This appears to be by design because control plus alt is used to signify AltGr, or the alternate shift key used on some non-US keyboards. The same mapping doesn't work for me in gvim either.

This is the comment I found in the VsVim code base:

```
                // Vim doesn't let you map Alt-Gr combinations, instead it sees the the character that is is output by the system 
                // key mapping. So in order to let VsVim behave the same way, the modifiers should be removed. Furthermore there's 
                // no special Alt-Gr modifier, it's rerpresented by Ctrl+Alt, so remove both of them. 
                // This fixes the #1008 and #1390 issues.
```
Here is an article that discusses the control plus alt problem:

- [Why Ctrl+Alt shouldn’t be used as a shortcut modifier](https://blogs.msdn.microsoft.com/oldnewthing/20040329-00/?p=40003)

**Comment by ricksladkey** [comment]
- Related to #1008
- Related to #1390

**Comment by ricksladkey** [comment]
Empirically, a `<A-S-x>` works in my VsVim, so certain alt combinations that avoid menu shortcuts can used as an alternative to the control plus shift modifiers.

**Comment by Murughavell** [comment]
Okay. Thanks a lot for the heads up. Sorry I couldn't find those cases on my own. Will try a bit harder before posting an issue!

**Comment by Widgertius** [comment]
Oh okay! Thanks a lot for the findings. Sorry I could not find it on my own. Will try harder before opening issues. Thanks again!
