### ISSUE TITLE
Cannot replace in visual selection with \%V

### ISSUE THREAD

**Issue by lucascebertin** [jaredpar/VsVim#2147]
I'm trying to replace some spaces with underscore in a selection with \%V and I get the message:
`Pattern not found: \%V`

Version: 2.5.0.0 on a VS2017 with reSharper enabled.

Example:
<a lot of spaces here>i want to replace the spaces between the words, not before the first word.

Hit `v` to select mode, select the entire phrase.
Hit `:` and the type the command ` :'<,'>s/\%V /_/g`

Expected:
<a lot of spaces here>i_want_to_replace_the_spaces_between_the_words,_not_before_the_first_word.

Please, consider `<a lot of spaces here>` with real spaces before the phrase (markdown remove empty spaces, so...).

Tested on VIM and works.

I don't know exactly if this is an expected behaviour, a bug or missing feature, so, issue opened.
BTW, vsvim helps me a lot... thanks for your time.

**Comment by ricksladkey** [comment]
This will be a lot easier to implement once substitution is converted to act on portion of the text buffer instead of individual lines.

See #1155

**Comment by lucascebertin** [comment]
This thing is going on or should I put my hands on it (maybe with a little assistance 😊)?

**Comment by ricksladkey** [comment]
Well, I understand the feature better, and I implemented multiline seaches, but getting the semantics exactly right for this will be impossible without writing our own regex engine.

Since we are using .NET (and/or Visual Studio) regex infrastructure, there is no way during pattern matching for the pattern to "break out" of the string being searched and answer questions about the world outside.

Basically, in vim, `\%V` is implemented as a zero-width predicate that just asks "is the character to the right of what I am matching right now within the visual selection?" Since there is no regular expression extensibility, there is no way for us to participate in the matching other than things we can put into the pattern.

In short, all we could do is do a check on whether the *whole* regular expression has matched inside the visual selection. Is that good enough?

**Comment by ricksladkey** [comment]
I tested this scenario in PR #2160 and it works. There is even a test based on it!
