### ISSUE TITLE
`:!` and `:r!` behave strangely

### ISSUE THREAD

**Issue by mfrischknecht** [jaredpar/VsVim#2167]
I've been trying to run `cmd` commands from VsVim on Windows 10 and I'm having some trouble with it:

If I run a command (e.g. `:! dir`), an empty CLI window opens up. As long as it stays open, Visual Studio is blocked (the GUI doesn't react anymore), and when I close the CLI window, the output of the command is finally displayed in the VsVim prompt. This also happens with commands that are non-built-in commands (e.g. `:! powershell -command ls`).

If I try to run an application detached from VsVim using `start` (e.g. `:! start cmd`), the additional application opens up correctly, but Visual Studio stays blocked until it is closed again. Interestingly, the CLI window that opens up on normal commands gets closed almost immediately.

If I try to insert the output of a command using `:r!` (e.g. `:r! dir` or `:r! powershell -command ls`), the VsVim prompt displays the message `Can't run X` (`X` being the specified command).

I'm currently running VsVim v. 2.5.0.0 in VS2015 on Windows 10.

**Comment by ricksladkey** [comment]
In the next released version of VsVim, the CLI window will no longer pop up, as the window will be hidden. Are you saying that on your system, the window (even if you run a command that exits right away, like `dir`) stays open until you close it?

As far as the blocking the main thread of Visual Studio, this is not a serious problem when filtering is working properly and the commands do their work quickly and exit. However, it is possible to design the running of commands so that it doesn't block the main thread, but would require considerable rework on the command infrastructure in VsVim. For now, don't run long-running commands.

As far as the `start` issue, I can reproduce that. It appears to be related to open pipes being inherited by the command which was started. I do not have a workaround or any clear idea at the moment how to solve it.

As far as `:r!` command, it is currently parsed but not implemented, which is why you see the `Can't run` message. It should be easy to implement using the new shell/filter support. I'll see what I can do.

**Comment by mfrischknecht** [comment]
> As far as :r! command, it is currently parsed but not implemented, which is why you see the Can't run message. It should be easy to implement using the new shell/filter support. I'll see what I can do.

Thank you very much!

> Are you saying that on your system, the window (even if you run a command that exits right away, like dir) stays open until you close it?

Exactly. The reason I tried `dir` and `powershell -command ls` is that `dir` is built into cmd (cf. `where dir`), whereas powershell.exe is a pre-installed binary (`where powershell`). The behavior seems consistent for both of them.

Regarding the hiding of the `cmd` window: I personally wouldn't mind it popping up if it closes after the command was run. If you try to hide it from the user, it would perhaps be a good idea to provide some easy way to kill a hanging command (`C-c` perhaps?). I guess that would mean the same amount of refactoring as the asynchronous execution though.

**Comment by ricksladkey** [comment]
I did find a workaround for the `start` problem. If you have Cygwin installed, you can use `cygstart` instead.

Here is a simple command prompt command that displays the pipe inheritance problem:

```
cmd /c start notepad | find "foo"
```

where the prompt is not returned until the asynchronous Windows program exits.
