### ISSUE TITLE
Folding seems to become a part of the undo-chain

### ISSUE THREAD

**Issue by sqlkoala** [jaredpar/VsVim#2184]
I noticed something that I find a bit weird ;-)
Repro:

1. Open a document that VS knows to fold
2. Delete a line
3. Open or close a fold
4. u for undo

Undo will undo the folding, not undo 2. A second undo will then restore the line.
I tested this two VsVims (2.4.xy and 2.5) in two VS (2015 and 2017 ).

**Comment by jaredpar** [comment]
Interesting. It looks like VS2017 at least is putting fold actions onto the undo stack.

**Comment by ricksladkey** [comment]
This apparently a longstanding and much-reviled "feature". Just read the User Voice comments:

https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3989085-exclude-outlining-operations-from-the-undo-redo-st

I was about to give up on a solution because VsVim relies heavily on the Visual Studio undo/redo history and it seems quite impossible for us to "skip" or otherwise exclude items that were externally added to the undo stack.

However, with a little poking around, I discovered an (undocumented?) option that we can set to prevent this behavior. Why this option is not exposed in the user interface (I couldn't find it anyway) is a little mystifying when so many people are begging for a solution and so bitter about lost data due to the "feature".

This single line of inserted code seems to do the trick:

```c#
            // Vim doesn't consider folding an undo operation, and neither does VsVim.
            vimBuffer.TextView.Options.SetOptionValue(DefaultTextViewOptions.OutliningUndoOptionId, false);
```

I will submit a PR as a proof-of-concept, but @jaredpar may have a better handle on how we should handle this.

**Comment by jaredpar** [comment]
I think that is the best approach. If we find any issues with this we can follow up with the VS team on them. Much better than trying to identify + skip them in the undo history.
