### ISSUE TITLE
repeat of change command does not match observed behavior in vim (example with 2cl)

### ISSUE THREAD

**Issue by Plotnus** [jaredpar/VsVim#2220]
The issue:

In vsvim it seams that the dot command isn't not repeating the insert with a change command.
Example below
---
In this example we are replacing "->" with "."

**In vsvim:**

```
foo1->bar(); // while on the "-" character "2cl" followed by "." yields "foo.bar();"
foo2->bar(); // while on the "-" character the repeat command "." yield "foobar();" 
```

**In vim:**
```
foo1->bar(); // while on the "-" character "2cl" followed by "." yields "foo.bar();"
foo2->bar(); // while on the "-" character the repeat command "." yields "foo.bar();"
```
---
Thanks again to everyone involved in this project. I really appreciate vsvim.
If this example is inadequate let me know.

**Comment by ricksladkey** [comment]
@Plotnus I am unable to reproduce the bug your are reporting, in either VsVim 2.5.0 or at the head of master. In fact, I myself perform the sequence you describe and repeat it many times a day, for example to rename an identifier.

So there must be something else going on here, and I can't offhand think what could be causing it. However, if this *were* broken, odds are many related things are also broken. So, as an experiment, can you describe the results of similar tests using these commands?

- `cw` (does it also misbehave?)
- `s` (should act exactly like `cl`)
- `o` (can you repeat an "open" command?)
- what happens if you type some other text than `.` as the new text?

Maybe this will help narrow down what is going on.

**Comment by Plotnus** [comment]
@ricksladkey Thanks for looking into this.

* I can repeat the 'o' comand
* I can repeat the 's' command
* I can repeat the 'cw' command. even 'c2w' works.
* when i type some other text instead of '.' it works fine.
It seems that all of the above misbehave whenever I have a '.' in the new text.

Here is some additional information:
- I'm using VsVim version 2.5.0.0
- I am using visual assist, maybe that is interfering

**Comment by ricksladkey** [comment]
@Plotnus Thanks for doing those tests. My suspicions are now around Visual Assist.

Do I understand you correctly that putting the cursor on the first `a` in `(abc) (abc)` and typing `cwx.y<Esc>` and then moving the cursor to the second `a` and pressing `.` will result in `(x.y) ()`? Or will it result in `(x.y) (xy)`?

If you can indulge me, can you do one more test. Try using the numeric keypad to enter the inserted `.`. This hunch is based on this possibly related issues #1875, #1971 and  #1777.

**Comment by Plotnus** [comment]
@ricksladkey 
Sorry about the delay. I use vsvim at the office and didn't have access to the setup.

When I did the test using (abc) you mention above in a lisp file I get the expected result (x.y) (x.y)
When i do the test in a .cpp file the result is (x.y) (y)
When i use the numeric keypad to insert the . the result is (x.y) (x.y)

Thanks again.

**Comment by ricksladkey** [comment]
I may have to install Visual Assist to figure this out. Here is a related issue with a similar symptom but with ReSharper: #1997.

**Comment by ricksladkey** [comment]
@Plotnus Can you try one final experiment for me? Try setting `:set vsvimatomicinsert` and then seeing if it affects whether the repeat works. If it does, then you can use that workaround (assuming it doesn't have any negative effects) and then I think I have a strategy for fixing the root problem.

**Comment by ricksladkey** [comment]
See PR #1552 which was intended to address problems with IntelliSense and Visual Assist and issue #664 which is (still!) open.

**Comment by Plotnus** [comment]
@ricksladkey 

Sure thing rick. I'll be able to do these tests and report back tomorrow when I have access to my work computer.

Thanks again.

**Comment by Plotnus** [comment]
@ricksladkey 
I know that this is slightly different that #664 because I did not use tab to autocomplete.
#1552 could be a fix. I'll try it tomorrow and let you know.

**Comment by ricksladkey** [comment]
@Plotnus I discovered in my own testing that you do not need to even use the autocomplete to have it interfere. Also, checkout out issue #1353, which is for ReSharper, where the problem is explicitly shown to occur without using completion.

**Comment by Plotnus** [comment]
@ricksladkey 
After running the ex command :set vsvimatomicinsert the command we used earlier for testing "cwx.y" _worked as expected when repeated using the dot command_.

If it doesn't take to much typing what is the fix strategy/theory?

**Comment by ricksladkey** [comment]
My approach, which is working out nicely, is to introduce the concept of "effective change". When you enter insert mode the active insertion region is empty. As you type, the active region grows to the right. As long as changes are made only within the active region, the buffer outside the region is unchanged.

If at the end of insert mode the effective change is "just an insert", then we don't care how we got there. The text within the active region is all that is new and the effective change is then an insert of exactly what you see on the screen.

Why this works is that the code assistants like Visual Studio, Visual Assist, and ReSharper all confine their activities to this "active region." They might move the cursor, or arbitrarily edit with insertions, deletions, and replacements, but we don't have to keep track of that. As long as they stay in the active region, we can easily reconstruct the inserted text simply by grabbing the text between the start and end of the active region. In that case, the effective change is just an insert even if the intermediate steps were quite complicated.

This is vastly simpler than trying to represent each micro-edit as a separate operation and building a long sequence of the text changes that will wind up inserting the effective change, as VsVim does now. The bad news is that VsVim does it the way it does (all the separate steps) for a good reason. For example, the backspace and delete operations can edit text outside of the active region and this prevents the effective change from being represented as a simple insertion.

Furthermore, there are other complications like tab which are context sensitive. If you type tab in one insertion, it may insert the appropriate number of spaces. When you repeat that insertion, you want the tab to insert the appropriate number of spaces for the new location, not simply paste what spaces where appropriate for somewhere else.

Anyway, I'm sorting through all of these issues, and ultimately we should be able to get the best of both worlds: we can use the effective change when it is applicable (and then we are immune to any interference from code assistants), but otherwise we use the old approach so that vim semantics are preserved and context sensitive operations can be properly repeated.
