### ISSUE TITLE
Extra space between command input edit control and editor

### ISSUE THREAD

**Issue by vanxining** [jaredpar/VsVim#2242]
On my machine, when I single click a file to preview it, there is extra space between the command input edit control and the editor.

If I pass the input focus to the editor, this extra space disappears.

I use VS 2017 15.7.4 and VsVim 2.5. And I tried the nightly build of VsVim but the same result.

Thanks!

![extraspace](https://user-images.githubusercontent.com/536291/42385408-476a80c0-816f-11e8-8ed9-1750427ba530.png)

**Comment by ricksladkey** [comment]
I can reproduce this bug. That rectangle is the VsVim "status line" and is only supposed to be visible when there is a status message. The status line visibility is updated when the document gets the aggregate focus and that is why focusing the buffer fixes the problem. The fix is to update the status line visibility in the command margin constructor.
