### ISSUE TITLE
VsVim unit tests which manipulate/depend-on the current directory may fail when run in parallel

### ISSUE THREAD

**Issue by ricksladkey** [jaredpar/VsVim#2254]
Certain VsVim unit tests either manipulate or depend on the state of the process-wide current directory. Running such tests in parallel may cause them to interfere with each. Those test should either be somehow marked as non-parallelizable, or altered so that they do not actually rely on the state of the process-wide current directory.

**Comment by jaredpar** [comment]
How are you attempting to parallelize the unit tests here?

The WPF editor tests would likely run in parallel okay but mostly because they'd all be running on the same thread via the `WpfFact` implementation. A few would fail though as they set shared resources such as the `SynchronizationContext`. 

Parallelizing at the `AppDomain` level should be feasible but within an `AppDomain` I would expect we'd hit some hard barriers with the WPF editor.

**Comment by jaredpar** [comment]
In either case though I agree we should isolate out the current directory. That's a fragile dependency to be taking even in non-parallel tests.

**Comment by ricksladkey** [comment]
It was some time ago that I was attempting to get the unit tests to run faster, and my report is based on my general impressions developed during that time.

I run the unit tests both from the "Test Explorer" (which has a "run in parallel" GUI option and from a command line script that I cobbled together based on what happens on appveyor. That script runs `Tools\xunit.console.x86.exe` which I tried to add `-parallel all` to and also tried to test all the assemblies with a single command. Retrying those experiments now, I cannot honestly say whether any of the tests are running in parallel or not because the parallel options don't seem to have any effect on how long the tests take.

However, I did get some tests to fail and contrary to the description of this issue, the problem in those cases seems to be direct manipulation of the environment variables for the current process, e.g. `GetVimRcFilePaths1` which like many tests runs `Environment.SetEnvironmentVariable`.

**Comment by jaredpar** [comment]
> It was some time ago that I was attempting to get the unit tests to run faster, and my report is based on my general impressions developed during that time.

Do you remember if this was before or after we moved to xUnit v2? That pretty radically changed how the tests worked and impacted how parallel operations ran.

**Comment by jaredpar** [comment]
I think in order to run in that much time a lot of investment would be needed in the `WpfFact` implementation. If you profiled that is likely what you would find was the bottleneck. 

Today it's a single STA thread that all tests essentially marshal onto. To parallelize this it would need to be a pool of `AppDomain` instances each of which held a single STA thread. It can't be done within the same `AppDomain` due to some fundamental limitations of the WPF editor code base. There is a bit of mutable state that is held in statics and if you attempt to access it from multiple threads it will cause errors. Hence have to use `AppDomain` instances to parallelizel the editor.

**Comment by ricksladkey** [comment]
Right now there are too many barriers to significantly shortening the time it takes to run the tests using parallelization, so I am closing this issue.
