### ISSUE TITLE
Delete and Search Bug

### ISSUE THREAD

**Issue by hacksoi** [jaredpar/VsVim#2257]
The following sequence seems to put me in an invalid state:
`d/<ESC>`
It looks like the focus gets stuck on the command line, with no way to unfocus from it except for closing the window.

**Comment by ricksladkey** [comment]
I can reproduce this bug. The issue seems to be that the buffer returns to normal mode (and not in a search), but the command margin stays in a command search state. Pressing further `<Esc>` keys have no effect because they are like pressing `<Esc>` in normal mode.

As a workaround, there are other keys you can press that incidentally synchronize the state between the buffer and the command margin, e.g. `<C-n>` and `<C-p>`.
