### ISSUE TITLE
vsvim repeats . once regardless of number prefix. Eg. ("4." behaves like "." instead of "...")

### ISSUE THREAD

**Issue by Plotnus** [jaredpar/VsVim#2259]
In vim if I insert text I can repeat it with the . command.
In vim if enter the kestrokes 4. it will repeat the dot command 4 times.
In vsvim 4. repeats the dot command once.

**Comment by ricksladkey** [comment]
Technically, vim and VsVim use the count supplied to the repeat command as the new count for the command that is being repeated. In any case, for the insert command, it is indeed much as though the insert was simply being repeated count times.

In any case, I cannot reproduce this bug with either VsVim 2.5.0 or the head of master. Offhand, I cannot think of any setting or circumstance that might cause it to appear as though the count to the repeat command was not implemented in VsVim, or otherwise cause it to misbehave.

**Comment by Plotnus** [comment]
Hi ricksladkey,
Thanks again for the help. It may be that some plugins are interfering. I don't know how they would. I'll check my VsVim version tomorrow at the office. Thanks for all your help on this plugin.

**Comment by ricksladkey** [comment]
Not sure why I didn't think this was reproducible previously, but it certainly is reproducible now.

The cause of the current problem is linked stored commands not properly inheriting the new count in `CommandUtil.RepeatLastCommand`.

**Comment by Plotnus** [comment]
@ricksladkey awesome rick. Thank you so much for taking the time to fix this issue. vsvim is awesome. I really appreciate it.

**Comment by Plotnus** [comment]
Sorry didn't mean to close the issue :/ my bad.

Still appreciate all the work :)
