### ISSUE TITLE
Any plan to support Rider?

### ISSUE THREAD

**Issue by farzadmf** [jaredpar/VsVim#2282]
Hi,

I love VsVim and that's one of the main reasons I keep using Visual Studio although I think it's too "heavy" (and slow) when used with lots of extensions.

As you probably know, JetBrains now has the Rider IDE. I've been trying it for a while, but, honestly, their own **ideaVim** plugin is ... well ... not as good.

I was wondering if you ever thought of providing an infrastructure to be able to use VsVim with other IDEs? Rider is an example. I know that their plugin infrastructure is totally different, but it would be really, really nice to have something as powerful as VsVim there.

VSCode is another example, the IDE that I love and I find the fastest one.

Thank you

**Comment by jaredpar** [comment]
The VsVim code base is heavily dependent on the VS editor APIs. It would be almost a complete rewrite to separate it from that. Hence I think it's very unlikely porting to a platform like Rider would ever be feasible here.

There are plans, or at least an understanding, of how to port VsVim to VS for Mac. That's because under the hood it uses the same editor API as VS proper. Hence this is actually more of a straight forward port vs. a rewrite. 

> VSCode is another example, the IDE that I love and I find the fastest one.

VSCode has an active vim plugin. If it's been a while since you've tried it I would recommend trying again. It's still younger than VsVim and hence less crisp in places but it's constantly improving.
