### ISSUE TITLE
Cannot paste in solution explorer

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#2283]
I can no longer use <kbd>Ctrl-V</kbd> to paste files into solution explorer. I suspect our changes to remove the copy / paste key bindings by default may be causing this. Haven't dug into it yet.

**Comment by ricksladkey** [comment]
I have not tested this yet, but it may be that if we configure the fallback key processor provider to apply to all views, not just interactive ones, it will correctly raise global commands like copy and paste for removed key bindings in the Solution Explorer.

**Comment by ricksladkey** [comment]
I looked into this enough to learn that there is no `IWpfTextView` associated with the Solution Explorer and so there is no possibility of us using a key processor to fix the problem as far as I can see. The workarounds to use `<A-e>P` or `<S-Insert>` are not ideal.

**Comment by dhmgit** [comment]
As far as I can tell, VsVim doesn't get a chance to process keys when Solution Explorer is focused, so VS key mappings are processed by VS within this context regardless of whether or not they are set to be "handled" by VsVim.  The problem looks like it has more to do with an overly broad removal of VS key assignments when those keys are set to be handled in VsVim.  In other words, I think the problem has more to do with configuration than live key event processing.

For example, I can explicitly assign CTRL-C, CTRL-V, and CTRL-P to their usual VS commands within the "Solution Explorer" context (see the "Use new shortcut in:" drop-down under Options>Environment>Keyboard). Even though I have CTRL-C and CTRL-V set to be handled by VsVim, these VS key assignments will work as expected when Solution Explorer has focus. Upon restart of VS, however, I lose my CTRL-C and CTRL-V key assignments because VsVim removes them. On the other hand, CTRL-P retains its assignment because it is NOT set to be handled by VsVim.

Can this problem be solved by changing VsVim to only remove VS key assignments in contexts in which VsVim has a shot at processing keys, such as the "Text Editor" context?  Or perhaps assignments in selected contexts such as "Solution Explorer" can be excluded from the removal?

I haven't looked into the code to see whether or not this is doable.  The one potential snag I can see is that the Global context is not completely "covered" by the union of all the available non-Global contexts.  In other words, there are views in VS that are only represented by the Global context.  So if I have contexts A, B, C and Global, we have (A + B + C) < Global where '<' means proper subset.  This means we can't describe the context (Global - B) as (A + C) because (A + C) < (Global - B).  In practical terms, when a VS key combination is originally assigned to a Global context, VsVim cannot reliably rewrite the assignment by replacing the Global assignment with a subset of non-Global assignments.

At the very least, however, it seems that VsVim could avoid removing key assignments for non-Global contexts within which it does not process keys, such as "Solution Explorer".  That way, explicit mappings within the Solution Explorer context (as described above) would be a viable workaround, even though they would need to be manually added.
