### ISSUE TITLE
Repeat last insert captures to much text with Intellisense

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#2341]
Assume that you're starting with the following code:

``` 
a.Method1();
a.Method1();
```

Cursor is positioned on the `M` on the first line. Then execute the following from normal mode: `cwMethod2<Tab><Esc>`. This assumes Intellisense shows up for `Method2` and that `<Tab>` completes this.

Now position the cursor on `M` of the second line and type `.`. The expected result is `a.Method2();` but is actually `a..Method2()`. This seems to happen because we capture the `.` incorrectly when the `<Tab>` completes the member.

**Comment by ricksladkey** [comment]
It's odd, but I cannot reproduce this bug with C#, VS2017 and the head of VsVim master. The strategy I used for debugging this kind of problem when I was working on the "effective change" PR is to:

1) Turn on VsVim logging to the output window
2) Issue the first `cwMethod2<Tab><Esc>` operation
3) Turn off VsVim logging to the output window
4) Copy the output window and filter it to all the lines containing `VsVim OnTextChange` between the typing of the `c` and the typing of the `<Esc>`
5) Reconstruct what edits took place as a result of the completion operation

This is enough information to write a test like the `ReSharperCompletion` test in `NormalModeIntegrationTest.cs`.

If I do those steps, I get:

- One insertion of each of the characters in the string `Method2` (typed by the user)
- A final replace operation that replaces `Method2` with `Method2` (when the user types `<Tab>`)

```
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = 'Method2', new = 'Method2'
VsVim OnTextChange: old = '[1220..1227)', new = '[1220..1227)'
VsVim OnTextChange: caret position = ?_v171_1227_'('`
```

and nowhere is a `.` ever inserted. As a result, I cannot repro an extra dot being inserted upon repeat.

But because I fear that the problem was introduced by a change that I made, I am eager to be able to reproduce it or at least to see the text changes that cause it.

**Comment by jaredpar** [comment]
Hmm. Wonder if I was only seeing this because I was using an internal build of VS. Let me see if I can track down why this isn't reproducing more generally.

**Comment by ricksladkey** [comment]
If it does only repro with an internal build of Visual Studio, then it almost certainly is still a VsVim bug, albeit of the same kind as "only repros with Resharper or Visual Assist". In other words, a different language service might complete things differently, but the "effective change" logic is supposed to correctly handle literally any edit that the language service performs behind the scenes. The "definitive answer" about what got eventually got inserted is always the text buffer itself.

**Comment by jaredpar** [comment]
I've been unable to reproduce this since my original filing. Tried a couple of different approaches now. Closing for now because there just doesn't seem to be any way to make progress here. Will reopen if I see this again.
