### ISSUE TITLE
Double-click on word incorrectly places block cursor

### ISSUE THREAD

**Issue by dhmgit** [jaredpar/VsVim#2367]
_Update: corrected problem description_

With `:behave xterm`

Upon double-clicking a word with the mouse:
* gVim selects the word with the block cursor over the last character
![image](https://user-images.githubusercontent.com/3457284/45525099-9ad2f600-b79f-11e8-9ad6-c38616edbcab.png)

* VsVim selects the word and places the block cursor over the first character following the word
![image](https://user-images.githubusercontent.com/3457284/45525077-868ef900-b79f-11e8-819c-8f4d38f32505.png)

Possibly related to #2366

**Comment by ricksladkey** [comment]
@dhmgit As you might imagine, I was just looking at this!

While double-click with `:set selection=inclusive` puts the character in the wrong place, the selection itself is correct and, for example, typing `y` will result in the proper text being yanked. In other words, the "extra" character under the caret is neither selected nor yanked.

But, yes, in short, the caret position is wrong.

Along the same lines, triple-click should switch to visual line mode and leave the caret where ever the mouse was clicked.

**Comment by dhmgit** [comment]
@ricksladkey that's funny, I just noticed the same thing.  I can see (when the cursor blinks off) that the selection doesn't include the character under the block cursor.

**Comment by ricksladkey** [comment]
All of these problems are caused by VsVim passively reacting to selection events resulting from Visual Studio's native mouse selection handling. The correct solution is somewhat complicated because we need to re-implement all the mouse selection handling ourselves. Drag was not that hard, but it breaks double and triple click, so we have to do the whole shebang, even recognizing multiple clicks.

I had already made some progress in this area and here's how far I've gotten:

https://github.com/ricksladkey/VsVim/tree/left-mouse
