### ISSUE TITLE
Option page support for marks display

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#2372]
Given the marks display is present in the UI think we should add an option page that helps control it's display. Mostly just surfacing the underlying option, `vsvim_hidemarks`, just as we do for a lot of other options.

One snag is that all of the settings we surface are global marks. Hence the effect of controlling them from a global UI is pretty straight forward: change in the global options UI and it affects every buffer. 

Controlling a local mark is a bit different. I think the user expectation is still that if I change the setting through the options UI then it should update my display everywhere. Yet it's a local mark so do we change only the active buffer, all of them, etc ...

Think about this I think there are a couple of options:

1. Make `vsvim_hidemarks` a global setting. 
1. Keep `vsvim_hidemarks` as a local setting but when it's changed in the UI manually update every buffer.

My intuition says to go with (1). My reasoning is that for me at least I can't think of when I would want two buffers two display a different set of marks. But I'm a UI minimalist and I could just be missing some key scenarios here. Wanted to see what others thought (particularly because I didn't implement this feature).

**Comment by ricksladkey** [comment]
I implemented mark hiding for two reasons:

- So you could turn off the feature entirely
- So that special marks you don't care about don't "clutter the gutter" or compete with marks you care about

I made it a local setting because somebody could conceivably want it to be different per buffer, but realistically I agree that this rather unlikely.

So I agree with (1), make `vsvim_hidemarks` a global setting.

**Comment by ricksladkey** [comment]
Closing this since it was completed by PR #2391.
