### ISSUE TITLE
VsVim and auto quote not playing nice together

### ISSUE THREAD

**Issue by Mehuge** [jaredpar/VsVim#2390]
Visual Studio 2017
VsVim installed (default settings, except `^F` and `^B` set to be handled by VsVim)

Editing an XML file.  Say I add an attribute to a node:

    <i>type="default"<ESC>

In reality, because Visual Studio is auto adding the quotes, I type

    <i>type=default<ESC>

If I don't I end up with doubled up quotes. I then want to replicate that edit on the next N nodes, so I move to position and press . (repeat last edit).

Unfortunately what happens is I get `type=default` added to the node, not `type="default"` which means I have to go back and edit each node, defeating the object of the repeat command.

**Comment by ricksladkey** [comment]
Thanks for taking the time to create a detailed bug report! The good news is that this bug was fixed in PR #2230 and the fix will be included in the next release of VsVim.

In the meantime, the workaround for the particular repro is to actually type both of the double quotes during the first insertion, that is to say ignore the fact that the language service auto-inserts them and type them anyway.
