### ISSUE TITLE
is it possible using vk_key code for vsvim?

### ISSUE THREAD

**Issue by SugeunOh** [jaredpar/VsVim#2395]
thank you for your hard work.

I was amazed when I first using spacemacs by VI Key mapping.
Because they support vi key mapping with Korean Input mode too.
it's means I don't have to change Language Mode(English, Korean).

for example, I have to change English language mode for moving cursor
but spacemacs allow moving cursor with Korean language mode by pressing "ㅗㅓㅏㅣ" (same position of "hjkl" of keyboard)

maybe there is a lot of people like me who using English as second language.

I think there is vk_key for getting same key input for both any language mode.

**Comment by sqlkoala** [comment]
Hi,
you can try a simple normal mode mapping, That would be an easy solution which you can build yourself.
Type ":" to get to the command line, then:
noremap  ㅗ <Left>
After that h/ㅗ should work as left movement. Does this work?

**Comment by ricksladkey** [comment]
In VsVim 2.6, you will be able to automatically turn off the IME when in normal mode, so if when using Korean input the `hjkl` keys produce latin characters when the IME is turned off, then not only will the caret motions work, but the whole vim command set.

However, whether or not this works, if you can reframe you request into a form that describes vim/gvim features instead of spacemacs/evil features, that will greatly increase the chance that it is either already supported or will be supported.

**Comment by SugeunOh** [comment]
WOW, I'm very expected VsVim 2.6 !!
I'm follow your suggestions for now on.
thank for your hard work!!
