### ISSUE TITLE
CTRL-W Window navigaton bug

### ISSUE THREAD

**Issue by kitsu** [jaredpar/VsVim#2435]
VS 2015R3, VSVim 2.6.0.0

For some reason `C-w j/k` regularly stop working for me.
In my latest case it works from any file tab except one.
After reading the internet I hit upon the fact  `C-w S-j/S-k` works from the misbehaving file tab.
After modifying my mappings (I use a leader mapping to C-w) and restarting VS I can now jump out of the offending tab... but cannot navigate from any other tabs/windows!
(Both upper and lower worked from the other tabs when I tested before restarting VS)

I have no idea what is going on, or how uppercase `K` is different from `k`.
I wouldn't mind so much, except the condition is persistent across restarts and I have no way to clear it.

**Comment by ricksladkey** [comment]
@kitsu Thanks for this report. If you could first answer what kind of document is the problematic one and what kind of screen layout causes the problem? A screenshot might help. Second, when the problem is exhibited is the symptom that you cannot "escape" the current window, i.e. that `<C-w>j`/`<C-w>k` seems to have no effect?

> I have no idea what is going on, or how uppercase `K` is different from `k`.

Using `<C-w>k` goes up"one window" and `<C-w>K` goes up "as far as possible". At least that's how it is *supposed* to work.

Some things to try:

- Try giving a count, e.g. `2<C-w>k` (this is effectively what using `K` does, but that supplies a large count)
- Try using `<C-w>w` to go to the "next" window (for a two window setup, this just goes to the other window)

If I had to guess, I'd say that somehow two windows are occupying or overlapping the same visible screen space, which I didn't think was possible. In gvim this is definitely not possible and windows are always "tiled" and not "overlapped". Visual Studio is superficially similar but with two caveats:

- Floating or auto-hiding windows can be made to overlap
- Various document types (e.g. XAML) have multiple interior windows

**Comment by kitsu** [comment]
Thanks for the insight on the logic/problems with VS window navigation.

Typically the problem occurs with **aspx** pages or **cshtml** (maybe it's html related?), and yes attempting to switch windows has no visible effect.

I just use one vertical split - just open a file, `:vspl`, open a different file in the new split, and close the duplicate.
BTW `:vspl` in an **aspx** file has no effect, and displays the error [Command "Window.NewWindow" is not available.]

Using `<C-w>w` (or `<C-w><C-w>`) seems to work, but only in one direction.

More strangeness: in an **aspx** file `<C-w>l` does not work on the first line, but does work on the next and apparently all subsequent lines. `Ν<C-w>l` also has no effect for any value of `Ν`.

``` aspx
<%@ Assembly Name="$SharePoint.Project.AssemblyFullName$" %> <%-- Doesn't work --%>
<%@ Import Namespace="Microsoft.SharePoint.ApplicationPages" %> <%-- Works --%>
```

(and yes I am stuck with these old technologies for some projects)

**Comment by ricksladkey** [comment]
First, regarding the latter problem (strangeness), this is a known issue caused by the navigation bar at the top of the other window. When on the first line, looking horizontally from the caret you can see that there is no line in the other window in which you could place the caret. At the moment, this seems like an acceptable quirk.

As far as the main issue, it turns out that **aspx** files behave very peculiarly in the Visual Studio editor. The main problem is that whether they are visible or hidden (not the active tab) the text view for an **aspx** file always reports `IsVisible` as `true`. This makes it impossible to know which document is actually displayed on screen in any tab group containing an **aspx** file.

I spent a fair amount of time trying to figure out a way to reliably answer this simple question:

- Is this text view displayed in the active tab of the containing document tab group?

but did not succeed.

Another oddity is that the text view for an **aspx** file does not appear anywhere in the visual tree of the current application, even when it has the focus.

**Comment by ricksladkey** [comment]
I finally found an API that returns a different result for an **aspx** document when it is not the selected tab of its tab group:

- [IVsWindowFrame.IsOnScreen](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivswindowframe.isonscreen?view=visualstudiosdk-2017)

Armed with this capability, the window navigation commands are now working in the presence of hidden **aspx** documents. However, some parts of VsVim depend or could depend on visibility change events and it is not clear that these events will work correctly for **aspx** documents.
