### ISSUE TITLE
cannot go to the last modified position by uisng `.

### ISSUE THREAD

**Issue by ppLorins** [jaredpar/VsVim#2440]
This problem occured after I installed another visutal studio plugin [Line Endings Unifier](https://marketplace.visualstudio.com/items?itemName=JakubBielawa.LineEndingsUnifier) several days ago , before which everything works well.  

> It says **mark not set** everytime I typed in  `.   And cursor won't go to the last modified position. 

After uninstall that plugin , vsvim recovered to normal. I suppose  that one violates the environment that vsvim based on .

Env: 
* visual studio community 2015  Version 14.0.25431.01 Update 3
* vsvim 2.6.0.0
* Line Endings Unifier 1.8.1

**Comment by ricksladkey** [comment]
I experimented with that extension, and while I cannot reproduce the exact symptoms, I'm fairly sure that the problem is a fairly general one:

- External text changes consisting of two or more separate changes cause the `LastEditPoint` mark to be cleared

For example, a "save all" operation that fixes the line endings in a file may cause a multi-part text change to be made, one change for each line ending fixed.

For single part external text changes, VsVim will move the "last edit point" to the end of the change. The most likely explanation for the bug is that the use of the specified extension greatly increases the likelihood of an multi-part external text change.

In any case, the problematic code in VsVim is almost certainly this block:

``` fsharp
            // When there are multiple changes it is usually the result of a projection 
            // buffer edit coming from a web page edit.  For now that's unsupported
            _vimTextBuffer.LastEditPoint <- None
```

**Comment by ppLorins** [comment]
Got . Thanks.
