### ISSUE TITLE
Cannot retrieve the previous Visual Span

### ISSUE THREAD

**Issue by mkujun** [jaredpar/VsVim#2446]
Can someone help me out with this issue? Maybe it has something to do with my vsvimrc file which looks like this:

nnoremap <S-j> :m+<CR>==
nnoremap <S-k> :m-2<CR>==
vnoremap <S-j> :m '>+1<CR>gv=gv
vnoremap <S-k> :m '<-2<CR>gv=gv

Multiple line movement in visual mode works only once, after that I get that error from the title. I'm using Visual Studio 2017.

**Comment by sqlkoala** [comment]
Hi,
Visual Studio has that feature "native". Does that solve your problem?
![image](https://user-images.githubusercontent.com/30384885/50344175-31931980-052a-11e9-8560-087bc314fc56.png)
I tried this to get to run with "your" keys, but that resulted in the same problem...
`vnoremap J :vsc Edit.MoveSelectedLinesDown<CR>`

**Comment by ricksladkey** [comment]
For the record, I think the full mappings being proposed are something like this:

```
nnoremap + :m .+1<CR>==
nnoremap - :m .-2<CR>==
vnoremap + :m '>+1<CR>gv=gv
vnoremap - :m '<-2<CR>gv=gv
```
These don't even seem to work correctly in vim. The error in VsVim is due to the old selection region being lost when the corresponding lines are deleted.

Here are some mapping that work with the current version of VsVim:

```
nnoremap + ddp
nnoremap - dd-P
vnoremap + dpV']
vnoremap - d-PV']
```
