### ISSUE TITLE
Add support for additional g commands

### ISSUE THREAD

**Issue by kalebpederson** [jaredpar/VsVim#524]
I'd like to see support for a few additional g commands:

- [x] `gE` go to end of previous word
- [x] `g~` Change case for motion (which I often use with `notildeop`)
- [x] `g0` Go to leftmost column visible on-screen character for current line (depends on `wrap`)
- [x] `g$` Go to last visible on-screen character for current line
- [x] `g^` Go to first visible on-screen character for current line
- [x] `g8` display hex value of byte(s) composing character under cursor

**Comment by themiwi** [comment]
Can't live without `g;` and `g,`. I find myself typing them all the time with no effect. Very aggravating.

**Comment by idealist1508** [comment]
@themiwi This workaround works for me (but i don't use something like that `5g;`)
```
nnoremap g; :vsc View.NavigateBackward<CR>
nnoremap g, :vsc View.NavigateForward<CR>  
```

**Comment by kitsu** [comment]
I just ran into a `g` command I'd like today: `gw` to 'go wrapped'.

I was editing a cshtml file and wanted to wrap a long line in a `<p>` at 80 characters (I have a guide-line there thanks to VS Productivity Power Tools). This is how I usual work with documentation in Vim/Evil-mode, and I was suprised it didn't work (since most things do in VsVim!).

For more detail `gw` takes a motion (or a visual selection) and hard-wraps it (i.e. adds `\n` after the last whole word ending before the wrap column). I think there is some variable that controls wrap width, but 79 or 80 are typical/default. I can't stand virtual wrapping, and with `JVgw` I can easily reformat hard wraps.
