### ISSUE TITLE
Show Vim Mapping in Keyboard Binding Options

### ISSUE THREAD

**Issue by hollasch** [jaredpar/VsVim#583]
Currently the options dialog for VsVim displays a description of the key bindings for Visual Studio, but not for Vim. It would be very helpful to show a description for both so user can more easily select which binding they want to use.

**Comment by jaredpar** [comment]
Thought about this some more and decided to not implement this behavior. The problem is that keys don't nicely correspond to Vim commands. There are a number of keys for which this is true but it gets complicated pretty quickly:

- Keys like `g` map to a huge number of commands
- Key mappings mean that different keys map to different commands for different users 

As such going to leave as is for now.
