### ISSUE TITLE
Completion with intellisense not repeatable.

### ISSUE THREAD

**Issue by rodimius** [jaredpar/VsVim#664]
Press 'i' type conso, then press tab to complete to Console, press escape.
. only repeats the conso part of the insert.
This works similarly for multiple completions in one insert.
I end up with lines like:
conso<tab>.R<tab>();

Version 1.1.0.0

**Comment by fredizzimo** [comment]
At least for the Visual Assist case, the undo grouping in the insert mode(https://github.com/jaredpar/VsVim/wiki/Vim-undo-grouping-in-Insert-mode) seems to be the biggest culprit.

Most cases, got fixed when I deleted the  _sessionData <- { _sessionData with CombinedEditCommand = None } line, from the OnCaretPositionChanged function in the Modes_Insert_InsertMode.fs file.

Visual Assist always updates the mouse cursor, when using intellisense, and resetting the session data clears all changes that have been made before that, which leaves only the last change, which in turn usually includes deletion of the first letters in the autocompleted word. Also if you have autocompletion of brackets turned on, the cursor will be moved inside the brackets, and you will get an empty repeat.

Unfortunately this modification breaks strict Vim compability when navigating with the mouse in insert mode, so I haven't made any pull request with that change. No unit tests were failing though, so some tests should probably be added for that case.

I think the best way to fix this would be to add some non-standard option, that will disable insert mode "undo-grouping" totally and threat all changes in the insert mode as one atomic insert. IMO, the grouping doesn't really make sense otherwise either. For example you see an error in some text that you typed, and want to correct it, so you navigate there with the arrow keys, but that means that you cannot repeat it anymore. I can't really think of any case where I would like to have the normal Vim behaviour, but that doesn't mean that there aren't any. You can always exit the insert mode, if you want a new group.

I will start experimenting with this now, and see if I can prepare a changelist that let's you disable the grouping by some option, to let you repeat exacty what was done in insert mode. Do you think that's a good idea? Also what should that option be called?

**Comment by jaredpar** [comment]
@fredizzimo this is an area where I think a non-standard option has to come into play.  Extensions like R# and Visual Assist do operations that just aren't comparable to what happens in gVim.

**Comment by ricksladkey** [comment]
This appears to work correctly now, and without setting `vsatomicinsert`, both in 2.5.0.0 and on master.

**Comment by ricksladkey** [comment]
Actually, I see that several issues are still being reported for this issue when either Visual Assist or ReSharper is present.

**Comment by ricksladkey** [comment]
I installed ReSharper and saw for myself how bad the repeat command is. There are two problems.

1) ReSharper (and Visual Assist according to @fredizzimo) moves the caret during not only completion with ReSharper IntelliSense but also when just typing.
2) Even if you try to solve the caret movement problem with `:set vsvimatomicinsert`, VsVim incorrectly deduces the effective text change associated with the insert

You can in fact reproduce a limited version of the problem with just Visual Studio by trying to repeat an insert that has auto-inserted parentheses, curly braces, square brackets, or quotation marks. Even though identifiers inserted by Visual Studio IntelliSense are faithfully repeated, these other auto-inserted characters don't repeat. These are the problems that `:set vsvimatomicinsert` was designed to solve, but it only partially works, and at a certain price due to bending vim semantics.

It seems possible to get the best of both worlds: vim semantics and reliable repeat. I have a prototype that introduces a concept of "effective change" that fixes both ReSharper completion and Visual Studio auto-inserted characters. I'll spend a little time trying to fill the gaps and make it production-ready.
