### ISSUE TITLE
cc doesn't put the cursor at indent if on empty line

### ISSUE THREAD

**Issue by philipmat** [jaredpar/VsVim#881]
[cc](http://vimdoc.sourceforge.net/htmldoc/change.html#cc) deletes the current line and places the cursor in insert mode (the 'autoindent' option determines its position).

VsVim doesn't always put the cursor in the right position. The one case I consistently managed to reproduce it is if you cc on an empty line it will place the cursor at the first column rather than at the indent.
Consider the following starting C# code ([ ] is the ncursor, | the icursor):

```
class Foo {
    public void Bar()
    [{]
    }
}
```

Press `o` to open line below:

```
class Foo {
    public void Bar()
    {
        |
    }
}
```

Now press `Esc`:

```
class Foo {
    public void Bar()
    {
[ ]
    }
}
```

Now press `cc`. This is where Vim and VsVim differ: Vim will place the cursor indented within the Bar:

```
class Foo {
    public void Bar()
    {
        |
    }
}
```

while VsVim will place it at line 0:

```
class Foo {
    public void Bar()
    {
|
    }
}
```

Alternatively, use this code:

```
class Foo {
    public void Bar()
    {
        throw new NotImplementedException()[;]
    }
}
```

In both Vim and VsVim a single `cc` will place the cursor in the indented position, but `cc<Esc>cc` will place the cursor at column 0 in VsVim (while Vim puts it at the right indent).

**Comment by wellspun** [comment]
This would still be a nice-to-have.  My intuitive sense is that the 'cc' to clear a line and begin editing should begin at the same indent level as creating a newline.  Is there an internal Vim/VS reasoning that this shouldn't be so?  I may tackle it as an inroad into working with the project.

**Comment by ricksladkey** [comment]
The solution to this problem was superficially nothing more than "do for `cc` whatever `o` was already doing" (which is why @shkm's workaround works), but the surgery necessary made it quite a bit more work.

VsVim was already doing the correct thing for so-called "vim indent," the kind of indent VsVim uses when there is no language service available. In order to add tests for this issue, I had to add infrastructure to the tests to simulate a language service. So the disconnect was that all the existing tests use "vim indent" but 99% of users are using "host indent", that is are editing files where Visual Studio provides and indent service.

To further complicate the problem, there was a bug that nobody ever reported with "vim indent" where it didn't work correctly when tabs were not being expanded (see issue #2302). Again, from a practical point of view nobody uses "vim indent" so upon reflection this isn't that surprising.
